### PR TITLE
CI: remove conflict label workflow

### PR DESCRIPTION
**Pull request by trim21**
fix https://github.com/PyGithub/PyGithub/issues/2668

@Borda

### CODE REVIEW

**Comment by trim21** [comment]
@EnricoMi

**Comment by trim21** [comment]
@EnricoMi

**Comment by EnricoMi** [comment]
I'd rather like to have the conflict label workflow removed as it is so unreliable: https://github.com/PyGithub/PyGithub/actions/workflows/label-conflicts.yml

**Comment by trim21** [comment]
> I'd rather like to have the conflict label workflow removed as it is so unreliable: https://github.com/PyGithub/PyGithub/actions/workflows/label-conflicts.yml

fine with me

**Comment by trim21** [comment]
@EnricoMi change this PR to remove it.

**Pull request merged**
