### PR TITLE
GithubIntegration: enable getting installation

### PR DESCRIPTION
**Pull request by TomasTomecek**
I tried adding this to the Repository class but since the request requires jwt token and the special headers, it was too much of a hassle.

~~I need a bit of help with adding replay tests.~~ Figured it out, ready for review.

Related #725 #828 #1021

### CODE REVIEW

**Comment by TomasTomecek** [comment]
can this be merged?

**Comment by ericofusco** [comment]
@TomasTomecek Installation can be done for organizations too. https://developer.github.com/v3/apps/#get-an-organization-installation
Does it make sense to have a new method to do this or use the org URI if repo is not given?

**Comment by TomasTomecek** [comment]
@ericofusco the code in this PR should be able to handle both

**Comment by ericofusco** [comment]
@TomasTomecek Maybe I missing something, new method only calls `/repos` endpoint. Accordingly to github docs to get an installation for an organization the URI is under `/orgs` path. Method from PR only gets an installation for a single repo, not for an organization (to manage members and teams for example).

**Comment by TomasTomecek** [comment]
@ericofusco oh, I misunderstood your previous comment. You/re right then.

**Comment by atodorov** [comment]
@TomasTomecek I am looking into the original comment in #725 where from the integration I want to get an installation via its specific ID and for that installation get all the repositories it can access. This PR seems to be different so can you explain a bit? 

I can work on adding what I need and send a PR but I need some context of what & how was done previously.

**Pull request merged**
