### PR TITLE
Support labels for PullRequests

### PR DESCRIPTION
**Pull request by s-t-e-v-e-n-k**
PullRequests can also have labels attached to them, like Issues or
Milestones. Extend PullRequest to also export them if they are present.

### CODE REVIEW

**Comment by sfdye** [comment]
@s-t-e-v-e-n-k Thanks for the PR, looks good! It will be cool if you could also add the edit/remove label methods to PullRequest 😄

**Comment by s-t-e-v-e-n-k** [comment]
I'd be delighted, I'll work on adding those methods and tests and force push.

**Comment by sfdye** [comment]
@s-t-e-v-e-n-k Awesome, I will wait for that.

**Comment by s-t-e-v-e-n-k** [comment]
@sfdye All done!

**Comment by sfdye** [comment]
@s-t-e-v-e-n-k Awesome work. Thanks!

**Pull request merged**
