### PR TITLE
Speed up get requested reviewers and teams for pr

### LINKED ISSUE #2348: [CLONE] Separate request for requested reviewers
@sfdye The response of listing pull requests already contains the requested reviewers' information. However, currently, if you want to list all requested reviewers for all pull requests, you must first list all pull requests (a paginated query) and then list request reviewers one pr by another (N paginated query), while you should have implemented it with only one paginated query.

That is, you should be able to fulfill the field with:

```python
        if "requested_reviewers" in attributes:
            self._requested_reviewers = self._makeIntAttribute(
                attributes["requested_reviewers"]
            )
```

_Originally posted by @tisonkun in https://github.com/PyGithub/PyGithub/issues/679#issuecomment-1301914566_

This can be a significant performance factor.

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #2348.

### CODE REVIEW

**Comment by tisonkun** [comment]
Locally tested. From several minutes to several seconds.

**Comment by tisonkun** [comment]
cc @sfdye @s-t-e-v-e-n-k

**Review by sfdye — APPROVED** [review]

**Comment by tisonkun** [comment]
Hi @sfdye! I wonder if there is a release cycle or trigger description. I'm depending on this fix to deploy one of my applications so I'd like to know how and when the patch will be released :P

**Comment by sfdye** [comment]
Released https://github.com/PyGithub/PyGithub/releases/tag/v1.57

**Comment by tisonkun** [comment]
Thank you!

**Pull request merged**
