### PR TITLE
fix(types): :label: align push restriction change stubs with impl

### PR DESCRIPTION
**Pull request by lbillinghamwrk**
In #1290 we changed the verbs in the methods for `def .*_{user,team}_push_restrictions` from `edit` to `replace`  It looks like we missed that change to the method implimentation in the typestubs. This PR re-synchronizes them.

implimentations at https://github.com/PyGithub/PyGithub/blame/master/github/Branch.py#L439 and https://github.com/PyGithub/PyGithub/blame/master/github/Branch.py#L472 

(as far as I can tell, the pyi stub files didn't exist at time of #1290)

### CODE REVIEW

**Comment by trim21** [comment]
@EnricoMi I think we should close this issue

**Comment by lbillinghamwrk** [comment]
> @EnricoMi I think we should close this issue

because of the conflicts or some other reason?
I can fix conflicts in the fork if y'all want

**Comment by trim21** [comment]
> > @EnricoMi I think we should close this issue
> 
> because of the conflicts or some other reason? I can fix conflicts in the fork if y'all want

file `github/Branch.pyi` has been removed

**Comment by treee111** [comment]
> file `github/Branch.pyi` has been removed

well if we don't want to add the `.pyi` files back this PR should be closed in my opinion to clean up a little bit.
@trim21 @EnricoMi

**Comment by EnricoMi** [comment]
I think [Branch.py](https://github.com/PyGithub/PyGithub/blob/main/github/Branch.py) is up-to-date.

**Pull request closed without merging**
