### PR TITLE
fix: totalCount always returns None

### PR DESCRIPTION
**Pull request by Tommos0**
#487
#415

### CODE REVIEW

**Comment by Tommos0** [comment]
https://github.com/PyGithub/PyGithub/issues/487
https://github.com/PyGithub/PyGithub/issues/415

**Comment by Tommos0** [comment]
Committed solution for totalCount will request more pages until it is exhausted to get the total count. There is a better way to get it in a single request (GitHub API returns a link to the last page in the header) - we can use this by setting `per_page = 1`. I'm using this as a workaround at the moment:

```python
def total_count(paginated_list):
    pars = paginated_list._PaginatedList__nextParams.copy()
    pars.update({"per_page" : 1, "page" : 1}) 
    headers, data = paginated_list._PaginatedList__requester.requestJsonAndCheck(
        "GET",
        paginated_list._PaginatedList__firstUrl,
        parameters=pars,
        headers=paginated_list._PaginatedList__headers
    )
    return int(re.match(r'.*[&\?]page=(\d*).*?rel="last"', headers['link']).group(1))
```

**Comment by k1-hedayati** [comment]
I'm having issue with empty `totalCount`, please accept this merge

**Comment by koglinjg** [comment]
To add to @Tommos0's workaround. I changed `return 1` to `return len(data)` to account for cases where the total count is `0`

**Comment by sfdye** [comment]
```
if not 'link' in headers:
	return 1
```

Should it `return 0` instead?

It seems that when the result is empty, the `Link` header will disappear.

**Comment by sfdye** [comment]
@Tommos0 Maybe a new PR for the more efficient total count?

**Comment by koglinjg** [comment]
@sfdye: I noticed that the `Link` header was not present if 0 or 1 results were returned. The data list will either be empty or have one result. So I think when the `link` header is not there just doing `len(data)` is the right thing to do.

**Comment by sfdye** [comment]
@koglinjg you are right.

**Comment by sfdye** [comment]
I'd prefer the `Link` header approach with setting `per_page` to 1. If someone can make a new PR for it I am more than happy to review.

**Pull request closed without merging**
