### PR TITLE
adds update_content function

### PR DESCRIPTION
**Pull request by jayfk**
This PR supersedes https://github.com/PyGithub/PyGithub/pull/316

I've pushed the changes to @ahmad88me's fork at first, but he was unresponsive for a couple of months.

Additionally to the original PR this adds:

* Support for both Python2 and Python3
* Tests
* A proper return value

### CODE REVIEW

**Comment by ahmad88me** [comment]
Hi @jayfk , I was too busy :grin: 

is there something pending from my side? :sweat_smile:

**Comment by jayfk** [comment]
Yeah, you have a PR open on your fork: https://github.com/ahmad88me/PyGithub/pull/1

If you could accept that it'll be attached to your PR on upstream so that the changes can be merged and I can close this one here :+1:

**Comment by ahmad88me** [comment]
@jayfk I accepted your changes

**Comment by jayfk** [comment]
:+1:

**Pull request closed without merging**
