### PR TITLE
Add support for draft pull request

### PR DESCRIPTION
**Pull request by ahhda**
Implements #1213 

* Added `draft` parameter to `create_pull` method. 
* Updated tests
* Updated docstring

### Testing

<details>
<summary>Automated testing</summary>

Screenshot 2020-03-07 at 2 47 47 AM

</details>

<details>
<summary>Manual testing</summary>

### With `draft = True`

1. Running the `create_pull` command:
Screenshot 2020-03-07 at 2 48 04 AM

2. Checking Github:
Screenshot 2020-03-07 at 2 48 20 AM

3. Checking the pull request
Screenshot 2020-03-07 at 2 48 33 AM

### With `draft` not set

1. Running the `create_pull` command:
Screenshot 2020-03-07 at 2 48 51 AM

2. Checking Github:
Screenshot 2020-03-07 at 2 49 03 AM

3. Checking the pull request:
Screenshot 2020-03-07 at 2 49 16 AM

</details>

### CODE REVIEW

**Comment by sfdye** [comment]
@ahhda Hey do you think it will be good to support the `draft` attribute like in #1100

**Comment by ahhda** [comment]
Hey @sfdye I was thinking we could add support for `draft` attribute over different atomic pull request's as compared to everything in the same pull request.

This PR is very similar to #703 and allows user to create draft pull requests. #1100 is implementing  the [list pull request API](https://developer.github.com/v3/pulls/#list-pull-requests).

Let me know if you still want both the features to be combined into one and I'll work on it.

**Comment by sfdye** [comment]
I like smaller and atomic PR. Let’s merge this first😁

**Comment by ahhda** [comment]
@sfdye Awesome! I have also rebased the branch.

**Comment by crizCraig** [comment]
🎉

**Pull request merged**
