### PR TITLE
Fixes #339 by allowing strings in the labels list.

### LINKED ISSUE #339: Allow strings in the labels list of create_issue
Labels can be added from strings and there is no reason strings can't be allowed in the list for issue creation.  The change requires relaxing the assertion and adding a conditional to the adding of labels to the post.

Currently
```python
repo.create_issue('name', body = "body", labels = [repo.get_label('label')])
```

After the Change
```python
repo.create_issue('name', body = "body", labels = ['label'])
```

### PR DESCRIPTION
**Pull request by crwilcox**
Labels can be added from strings and there is no reason strings can't be allowed in the list for issue creation.  The change requires relaxing the assertion and adding a conditional to the adding of labels to the post.

Currently
```python
repo.create_issue('name', body = "body", labels = [repo.get_label('label')])
```

After the Change
```python
repo.create_issue('name', body = "body", labels = ['label'])
```

### CODE REVIEW

**Comment by jzelinskie** [comment]
If the label doesn't already exist, does it create one from the string?

**Comment by crwilcox** [comment]
@jzelinskie Yes. It will create a label from the string if it doesn't exist.

**Comment by jzelinskie** [comment]
@crwilcox if you add a test, I'll merge it! :+1:

**Comment by crwilcox** [comment]
Just added a test now.  Thanks!

**Comment by jzelinskie** [comment]
LGTM

**Pull request merged**
