### PR TITLE
Add support to self-hosted runner to organization level

### PR DESCRIPTION
**Pull request by jorgegarciarey**
Hi team,

I would like to add some methods to be able to manage the self-hosted runners  to organization level like:
- [`get_self_hosted_runners`](https://docs.github.com/en/rest/reference/actions#list-self-hosted-runners-for-an-organization)
- [`get_self_hosted_runner`](https://docs.github.com/en/rest/reference/actions#get-a-self-hosted-runner-for-an-organization)
- [`remove_self_hosted_runner`](https://docs.github.com/en/rest/reference/actions#delete-a-self-hosted-runner-from-an-organization)

Anything you need, let me know, please.

### CODE REVIEW

**Comment by jorgegarciarey** [comment]
@s-t-e-v-e-n-k friendly reminder 😃

**Comment by jorgegarciarey** [comment]
@s-t-e-v-e-n-k  ✋🏽

**Comment by ppalucha** [comment]
@s-t-e-v-e-n-k Can you re-review? I also found this API missing and was thinking of contributing, but since PR is already there...

**Review by seemethere — APPROVED** [review]

**Comment by taliamax** [comment]
Can @s-t-e-v-e-n-k 's review be dismissed? This PR also needs to be rebased on master @jorgegarciarey, shouldn't cause any conflicts

**Comment by jorgegarciarey** [comment]
@s-t-e-v-e-n-k , @sfdye  ?

**Comment by Haagy** [comment]
Any future for this to be merged?

**Comment by nilesingalls** [comment]
I could really use this feature

**Comment by sfdye** [comment]
Tests are failing

**Pull request closed without merging**
