### PR TITLE
merge annotation with `retype`

### PR DESCRIPTION
**Pull request by Borda**
as mentioned in https://github.com/PyGithub/PyGithub/issues/2589#issuecomment-1620480319 as min Python version is 3.7 we do not need to have annotation in external files, and all can be in this package... Some advantages:

- typing, defaults, and method/function footprint lives in the same place
- reduce the number of files in the uniform folder
- simplify navigation and development as pyi are not commonly used any more

### CODE REVIEW

**Comment by trim21** [comment]
I tried this beforee, but it won't work for some reasons:

1. circle import
2. There is a old style `... is NotSet` or `... is not NotSet` and need to be updated to `is_defined` or `is_undefined`
3. some type stub are wrong, and some inline code can't narrow type, so it failed on mypy

**Comment by Borda** [comment]
> I tried this beforee, but it won't work for some reasons:
> 
> 1. circle import
> 2. There is a old style `... is NotSet` or `... is not NotSet` and need to be updated to `is_defined` or `is_undefined`
> 3. it doesn't add instance attributes
> 4. some type stub are wrong, and some inline code can't narrow type, so it failed on mypy

so how about making this per file and trying to resolve it in smaller steps?

**Comment by trim21** [comment]
> > I tried this beforee, but it won't work for some reasons:
> > 
> > 1. circle import
> > 2. There is a old style `... is NotSet` or `... is not NotSet` and need to be updated to `is_defined` or `is_undefined`
> > 3. it doesn't add instance attributes
> > 4. some type stub are wrong, and some inline code can't narrow type, so it failed on mypy
> 
> so how about making this per file and trying to resolve it in smaller steps?

That's what I'm doing https://github.com/PyGithub/PyGithub/pulls/trim21

**Comment by trim21** [comment]
I have done many classes in https://github.com/PyGithub/PyGithub/pull/2570 , would you mind choose the rest class, so neither of us will do useless work?

**Comment by Borda** [comment]
closing in favor of #2576

**Comment by Borda** [comment]
> would you mind choose the rest class, so neither of us will do useless work?

ok, I can, let's just wait till yours is merged and I can continue

**Pull request closed without merging**
