### PR TITLE
Adding delete_review_function

### PR DESCRIPTION
**Pull request by sameer1996-cmd**

### CODE REVIEW

**Review by sameer1996-cmd — COMMENTED** [review]
.

**Comment by sameer1996-cmd** [comment]
@s-t-e-v-e-n-k  my checks are failing here for one of the files, can you please take a look?

**Comment by s-t-e-v-e-n-k** [comment]
@sameer1996-cmd You have 3 pull requests open with different changes and different commits, would you mind closing the ones that are not needed and comment on the one that is correct?

**Comment by s-t-e-v-e-n-k** [comment]
Thank you for your work, but please push up one pull request for this, and I'll review that.

**Pull request closed without merging**
