### PR TITLE
Add minimize and unminimize functions for IssueComment class

### PR DESCRIPTION
**Pull request by arash77**
This pull request adds two new functions, `minimize` and `unminimize`, to the `IssueComment` class. These functions allow users to minimize and unminimize comments using the GitHub GraphQL API. The `minimize` function takes an optional reason parameter and sends a mutation to minimize the comment. The `unminimize` function sends a mutation to unminimize the comment. These functions provide more control and flexibility for managing comments in GitHub issues.

### CODE REVIEW

**Review by EnricoMi — APPROVED** [review]
LGTM! Looks like we need GraphQL testing capabilities in this project.

**Review by EnricoMi — CHANGES_REQUESTED** [review]
Looks like there is testing available. Can you add some tests for those two new IssueComment methods?

**Comment by arash77** [comment]
> Looks like there is testing available. Can you add some tests for those two new IssueComment methods?

I added the tests. Are they enough?

**Comment by EnricoMi** [comment]
I have added missing test data.

**Comment by arash77** [comment]
> I have added missing test data.

Thank you so much!

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Pull request merged**
