### PR TITLE
Add `message` property to `GithubException`

### PR DESCRIPTION
**Pull request by trim21**
close https://github.com/PyGithub/PyGithub/issues/2589

### CODE REVIEW

**Comment by EnricoMi** [comment]
Ome `GithubException` has a non `dict` values for `data`, it's used as a message string:
https://github.com/PyGithub/PyGithub/blob/8d3b905786102d4b1890523932a8212cad56e88a/github/GithubObject.py#L380-L382

**Comment by trim21** [comment]
> One `GithubException` has a non `dict` values for `data`, it's used as a message string:
> 
> https://github.com/PyGithub/PyGithub/blob/8d3b905786102d4b1890523932a8212cad56e88a/github/GithubObject.py#L380-L382
> 
> Maybe, this one should be derived from `Exception`, because the `IncompletableObject` exception does not come from Github, but it is the user's fault. While we are there, it could be renamed to `IncompletableObjectException`.

why mypy doesn't find this...

**Comment by trim21** [comment]
I have no better idea about how to fix this...

**Comment by EnricoMi** [comment]
> I have no better idea about how to fix this...

What about an optional exception message (additional argument)?

**Comment by trim21** [comment]
> > I have no better idea about how to fix this...
> 
> What about an optional exception message (additional argument)?

what about current patch?

**Comment by EnricoMi** [comment]
I wouldn't mix the error message into the `data` field, I'd rather have an optional string `msg` field.

All exceptions should have a message field to provide some extra meaning additional to the exception type. The `__repr__` could nicely use this.

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Pull request merged**
