### PR TITLE
Don't merge

### PR DESCRIPTION
**Pull request by jacquev6-tests**
This is @jacquev6 trying to fix integration with travis-ci.

### CODE REVIEW

**Comment by jacquev6** [comment]
Looks promising:

screen shot 2016-01-11 at 11 06 54

**Comment by jacquev6** [comment]
OK, not so promising :-)

screen shot 2016-01-11 at 11 08 31

**Comment by jacquev6** [comment]
The failures on this PR (https://travis-ci.org/PyGithub/PyGithub/jobs/101546963) are the same as the current failures on master (https://travis-ci.org/PyGithub/PyGithub/jobs/100904663), which was broken by merging #372.

@jzelinskie I've deactivated Travis and re-activated it, and now it is able to annotate PRs again. If this is what you were wondering about, just close this PR. Else, let me know :-)

**Comment by jzelinskie** [comment]
Thanks!

**Pull request closed without merging**
