### PR TITLE
Add `license` attribute to `Repository`

### PR DESCRIPTION
**Pull request by mxmehl**
The GitHub API behind `.get_repo()` also delivers licensing information, but PyGithub doesn't pick it up. This Pull Request changes that.

It extracts the SPDX license ID, IMHO the most important information which is provided and with which a user can get more information (like the license text or full name).

This is my first contribution ot the project and I hope it meets your requirements.

### CODE REVIEW

**Comment by EnricoMi** [comment]
It'd be better to have a `Repository.license` attribute that returns a `github.License.License` instance, which already implements the `spdx_id` attribute.

See `organization` as an example of how to have a class attribute:
https://github.com/PyGithub/PyGithub/blob/bcca758d13ef466a7ae13f4d9d99689ba0043640/github/Repository.py#L4067-L4068

**Comment by mxmehl** [comment]
> It'd be better to have a `Repository.license` attribute that returns a `github.License.License` instance, which already implements the `spdx_id` attribute.

That makes complete sense. I didn't think it was that easy.

I've updated the PR and tested it locally:

```py
from github import Github

gthb = Github()
repo = gthb.get_repo("PyGithub/PyGithub")

print(repo.license.spdx_id)
```

**Review by EnricoMi — CHANGES_REQUESTED** [review]
This looks good. Can you please add this attribute to `Repository.testAttributes` in `tests/`? You will have to add the `attributes` field with some example licence JSON object to `tests/ReplayData/Repository.setUp.txt`.

**Comment by mxmehl** [comment]
> This looks good. Can you please add this attribute to `Repository.testAttributes` in `tests/`? You will have to add the `attributes` field with some example licence JSON object to `tests/ReplayData/Repository.setUp.txt`.

Sure, I hope I understood it correctly. Please review the latest commit, thank you!

**Comment by EnricoMi** [comment]
Looks exactly like what I meant, thank!

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Comment by mxmehl** [comment]
Great, thanks for the quick review and positive words. It has been a please to contribute :)

Looking forward to the next release!

**Pull request merged**
