### PR TITLE
Add missing fields from `GithubCredentials.py` to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by JLLeitschuh**

### CODE REVIEW

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Comment by EnricoMi** [comment]
@JLLeitschuh feel free to "Squash and merge" into master.

**Comment by JLLeitschuh** [comment]
Can we make that the default via the repository settings?

**Comment by EnricoMi** [comment]
See the Slack discussion...

**Pull request merged**
