### PR TITLE
Drop Python 2 support

### PR DESCRIPTION
**Pull request by s-t-e-v-e-n-k**
With the Python 2 deadline fast approaching, it's time to move with the
times and switch to Python 3 only.

### CODE REVIEW

**Comment by s-t-e-v-e-n-k** [comment]
@sfdye What do you think? Should we merge this, and worry about increasing coverage in some separate PRs?

**Comment by sfdye** [comment]
👍 for merging. 

Did you use some tools to generate this PR?

**Comment by sfdye** [comment]
Some docs still have reference for Python 2, e.g.
`PyGitHub is a Python (2 and 3)`
https://github.com/PyGithub/PyGithub/blob/master/README.md#pygithub

**Comment by s-t-e-v-e-n-k** [comment]
Mostly ``sed`` if I'm honest. :-)

**Pull request merged**
