### PR TITLE
Add has_discussions field to Repository class

### LINKED ISSUE #2994: Configure repository discussions
I want to enable/disable Discussions in my repositories.

`Repository.edit()` does not have a `has_discussions` field. Is there another way of doing that?

### PR DESCRIPTION
**Pull request by heitorPB**
Add property and configuration of GitHub discussions per repository.

Fix #2994

### CODE REVIEW

**Comment by heitorPB** [comment]
I don't know what's going on...

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Comment by EnricoMi** [comment]
Looks like this PR is incomplete.

**Comment by heitorPB** [comment]
What's missing @EnricoMi ?

**Comment by EnricoMi** [comment]
This PR is inconsistent, it adds `has_properties` attribute but tests `has_discussions`.

**Comment by heitorPB** [comment]
Ouch, my multitasking skills are so bad I mixed stuff around.

What do you suggest as a followup?

**Comment by heitorPB** [comment]
Btw, the issue should be re-opened, right?

**Comment by EnricoMi** [comment]
> What do you suggest as a followup?

Undelete your branch, fix the branch and create a new pull request.

**Pull request merged**
