### PR TITLE
add has_organization_projects and has_repository_projects

### PR DESCRIPTION
**Pull request by jdelic**
These are just two missing booleans from https://developer.github.com/v3/orgs/#get-an-organization

### CODE REVIEW

**Comment by sfdye** [comment]
Thank you @jdelic would appreciate some unit tests though.

**Comment by jdelic** [comment]
I'm still working on this. Getting tests done and creating a new test org to do so will take some time.

So...  🤖👉🚪

**Comment by jdelic** [comment]
Still planning on creating a new test org. I have a couple of vacation days coming up, so this might actually happen.

**Comment by s-t-e-v-e-n-k** [comment]
Silence, stalebot, this just needs unit tests.

**Pull request closed without merging**
