### PR TITLE
Handle white-spaces in name in Organization and AuthenticatedUser 

### PR DESCRIPTION
**Pull request by ionicc**
Closes: #1622

* Added stripping of leading and ending white spaces for in name in AuthenticatedUser and Organization
* Added replacement of white space in between the text with "-"

### CODE REVIEW

**Comment by ionicc** [comment]
@s-t-e-v-e-n-k By ugly, Are you referring to the implementation? Simple replace would not deal with the leading and ending whitespaces. Also, strip would strip the spaces between the org name as well.

**Comment by s-t-e-v-e-n-k** [comment]
@ionicc strip() doesn't work like that.

```
>>> foo = '    test string '
>>> foo.replace(" ", "-")
'----test-string-'
>>> foo.strip().replace(" ", "-")
'test-string'
>>> 
```

Replacing spaces with a - I can understand because spaces will get URL encoded, but why strip(), that is just working around issues that callers should be dealing with.

**Comment by ionicc** [comment]
> strip() doesn't work like that.
@s-t-e-v-e-n-k  My bad on that, Didn't see the implementation of strip() before implementing lstrip and rstrip. But as you said, Giving a more descriptive exception would be good.

**Comment by jesseli2002** [comment]
Question - might be a slippery slope argument, but there's a bunch of prohibited characters for a repository name on Github (most symbols, I imagine most Unicode characters too. Brief experimentation suggests that Github combines any contiguous string of these into a single dash.)

If validation is going to be done for spaces, wouldn't that imply validation should be done for all other characters?

**Comment by ionicc** [comment]
@jesseli2002 True. Maybe instead of validation, Meaningful exceptions should be given rather than getting `UnknownObjectException` on any validation issue.

**Pull request closed without merging**
