### PR TITLE
Correct typos found with codespell

### LINKED ISSUE #1459: Typos discovered by codespell
`%` [codespell](https://github.com/codespell-project/codespell) `--ignore-words-list="bloaded,nto,pullrequest,pullrequests,thi,tim,wan" --quiet-level=2 --skip="./tests/*"`
```
./doc/introduction.rst:71: automaticaly  ==> automatically
./doc/changes.rst:558: compatability  ==> compatibility
./doc/changes.rst:652: corrensponding  ==> corresponding
./doc/changes.rst:762: automaticaly  ==> automatically
./github/GitRelease.py:218: ommited  ==> omitted
./github/GitRelease.py:219: alltogether  ==> altogether, all together
./github/__init__.py:33: instanciate  ==> instantiate
./github/ProjectCard.py:115: Unforunately  ==> Unfortunately
./github/MainClass.py:709: optionaly  ==> optionally
./github/MainClass.py:721: informations  ==> information
./github/StatsContributor.py:40: contibutor  ==> contributor
```

### PR DESCRIPTION
**Pull request by s-t-e-v-e-n-k**
Correct misspellings and typos located using the codespell tool.

Fixes #1459

### CODE REVIEW

**Comment by s-t-e-v-e-n-k** [comment]
@cclauss I tried to add codespell to pre-commit, but I couldn't get your ignore list to work inside pre-commit :-(

**Comment by cclauss** [comment]
```
    hooks:
      - id: codespell
        args:
          - --ignore-words-list="bloaded,nto,pullrequest,pullrequests,thi,tim,wan"
          - --quiet-level=2
          - --skip="./tests/*"
```

**Comment by s-t-e-v-e-n-k** [comment]
@cclauss Thanks! I've not used exactly that, but it gave me enough of a nudge.

**Comment by cclauss** [comment]
> I've not used exactly that, but it gave me enough of a nudge.

Yes.  I have gotten used to the [not invented here](https://github.com/PyGithub/PyGithub/pulls?q=is%3Apr+author%3Acclauss+is%3Aclosed) approach that this repo uses.

**Comment by s-t-e-v-e-n-k** [comment]
Come on, that isn't fair. Surely the goal is the problem gets solved, not whose name is on the commit? Besides, if you compare what I committed and what you had, you'll see there's a difference.

**Pull request merged**
