### PR TITLE
Add highlight search to search_code function

### LINKED ISSUE #591: Support highlighting-code-search-results?
https://developer.github.com/v3/search/#highlighting-code-search-results-1

### PR DESCRIPTION
**Pull request by AnYeMoWang**
Closes #591

The original ```search_code``` function in ```MainClass.py``` dose not support highlight search, so I added highlight parameter in this function and completed it (according to [highlighting-code-search](https://developer.github.com/v3/search/#highlighting-code-search-results-1) ). 
Now we can call it like this~

### CODE REVIEW

**Comment by sfdye** [comment]
This is awesome! I will be more convinced if you can add a unit test for the added highlight function 😄

**Comment by sfdye** [comment]
@AnYeMoWang Thanks for your contribution. Don't worry I have fixed the tests in master.

**Comment by AnYeMoWang** [comment]
I've ran ```python -m github.tests Search.testSearchHighlightingCode --record --auth_with_token``` and it passed. But I saw that it failed with Travis CI. When you changed ```token private_token_removed```, it passed. So what's the problem~

**Comment by sfdye** [comment]
@AnYeMoWang Stupid ancient testing framework, that's why.

**Pull request merged**
