### PR TITLE
Add team privacy parameter to create team

### PR DESCRIPTION
**Pull request by res0nance**
Implements #611 

Replay data is still not correct as I was unable to to run with the record parameter leading to issues such as attempting to write a str object to a binary file. Input being None for RecordingConnection.request. Fixing the above 2 led to a 404 error. Could someone direct me on how to properly obtain the recording data?

### CODE REVIEW

**Comment by calebgroom** [comment]
@res0nance Can you pull my commit into your branch? It should sort out your testing failures.

**Comment by res0nance** [comment]
@calebgroom Thanks it seems to have fixed it.

It seems like the testing framework does not support python 3 and some tests seem to be broken when trying to record. I'm not certain if there is an issue for that yet.

**Comment by grahamlyons** [comment]
Very glad to see someone has tackled this - thank you.

**Comment by sfdye** [comment]
Thanks @res0nance and @calebgroom !

**Pull request merged**
