### PR TITLE
Implement repo content create/update/delete file API

### PR DESCRIPTION
**Pull request by enix223**
I have done the following changes to PyGithub:

1. implement the following 3 API under repositories
PUT /repos/:owner/:repo/contents/:path  <http://developer.github.com/v3/repos/contents#create-a-file>
PUT /repos/:owner/:repo/contents/:path  <http://developer.github.com/v3/repos/contents#update-a-file>
DELETE /repos/:owner/:repo/contents/:path  <https://developer.github.com/v3/repos/contents/#delete-a-file>

2. Fix `testGetContents` and `testGetContentsWithRef` path error.
A preceding slash is missing before `doc` folder, so they will be pointed to a wrong URL as below:
`/repo/contentsdoc/ReferenceOfClasses.md`

Test cases are prepared for those 3 new APIs. All test have been run without error. Please check and comment.

### CODE REVIEW

**Comment by jayfk** [comment]
`update_file` should return the `Commit` and the `ContentFile`, see https://github.com/ahmad88me/PyGithub/commit/b0cf9b524af9c4cd5a44fa6cce637d132b552929 

I'd be super happy if this PR gets merged. It basically replaces #369/#316

**Comment by jakirkham** [comment]
Could we please get a review of this PR? This is an incredibly useful addition.

**Comment by jakirkham** [comment]
cc @pelson

**Comment by enix223** [comment]
@jayfk  Thanks for your comment. I have update the return value for create/update/delete to include commit value in the return type, but I think a dict with commit and content is more appropriate than a tuple. [(https://developer.github.com/v3/repos/contents/#update-a-file)]

**Comment by jakirkham** [comment]
Looks like there are some merge conflicts.

**Comment by jayfk** [comment]
Thanks 👍

**Comment by jakirkham** [comment]
Nice!

**Comment by jakirkham** [comment]
Is there a release planned that may include these changes?

**Pull request merged**
