### PR TITLE
Fix GraphQL Queries with Variables

### PR DESCRIPTION
**Pull request by kgal-pan**
Fix https://github.com/PyGithub/PyGithub/issues/3001

### CODE REVIEW

**Comment by EnricoMi** [comment]
@heitorpolidoro what are your thoughts?

**Comment by EnricoMi** [comment]
@kgal-pan please rebase with / merge current main branch.

**Comment by kgal-pan** [comment]
> @kgal-pan please rebase with / merge current main branch.

Done.

**Comment by EnricoMi** [comment]
Look like the input is needed by mutations. Adding fix in a minute.

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Comment by kgal-pan** [comment]
@EnricoMi  - Any ETA on the next release? Thanks! 🙏🏾

**Comment by heitorpolidoro** [comment]
> @heitorpolidoro what are your thoughts?

Sorry for the delay.
It it a good fix. ✅ 

Thanks @kgal-pan

**Pull request merged**
