### PR TITLE
Note explicit support for Python 3.5

### PR DESCRIPTION
**Pull request by felixonmars**

### CODE REVIEW

**Comment by sils1297** [comment]
Any reason travis doesn't build this one?

**Comment by felixonmars** [comment]
Maybe you didn't configure travis for this repo? I didn't see travis in other PR either.

**Comment by sils1297** [comment]
That would be weird. I'm not associated with this repository, I just want this PR merged too though ;)

**Comment by felixonmars** [comment]
Ah, sorry. I meant that the repo's owner may not have enabled travis yet.

**Comment by sils1297** [comment]
ah seems to be https://github.com/PyGithub/PyGithub/issues/338

**Comment by jzelinskie** [comment]
Yes, travis is blocked until the original author sets things up again. He did not give enough permission to any of the maintainers to fix it.

**Comment by jakirkham** [comment]
What if you try merging with current `master`? Would that fix it?

**Comment by jzelinskie** [comment]
The problem with travis has since been resolved. If this branch is rebased, we can merge it.

**Comment by felixonmars** [comment]
Sorry for the late response. I have rebased the branch now.

**Pull request merged**
