### PR TITLE
Add missing properties to Repository

### PR DESCRIPTION
**Pull request by jacquerie**
Closes #784
Closes #785

First commit fixes a small bug that I observed while trying to record some new test fixtures: the stringification of the headers is not correctly printed as a list of tuples, but as an `iteritems` object, so I forced the list evaluation.

Second commit adds the missing properties `allow_merge_commit`, `allow_rebase_merge`, `allow_squash_merge`, and `has_projects` to the `Repository` class.

Note however that I ran into some trouble while modifying the `edit` method of the `Repository` class to make use of the new properties, specifically while writing tests, so I will fix the `edit` method in a future PR.

### CODE REVIEW

**Comment by jacquerie** [comment]
Mh, I just noticed that this work was already attempted in https://github.com/PyGithub/PyGithub/pull/784 and https://github.com/PyGithub/PyGithub/pull/785...

**Comment by sfdye** [comment]
Yes, they did not get merged due to lack of unit tests. So if you don't mind..

**Comment by sfdye** [comment]
Good spot for the `iteritems` issue btw!

**Comment by jacquerie** [comment]
> Yes, they did not get merged due to lack of unit tests. So if you don't mind..

Sure thing! I modified the existing tests for `AuthenticatedUser` and `Organization`.

**Comment by sfdye** [comment]
@jacquerie Awesome work! Thank you so much.

**Pull request merged**
