### PR TITLE
Feat: Add missing branch protection fields incl. lock_branch

### LINKED ISSUE #2373: github.BranchProtection.BranchProtection missing 3 attributes
This is duplicate of issue [1716](https://github.com/PyGithub/PyGithub/issues/1716) (closed by StaleBot).

GitHub api provides to do the following:

    required_linear_history: true,
    allow_force_pushes: true,
    allow_deletions: true

https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-branch-protection

The functions related to this 3 branch protection rules are not added in the class mentioned in the title.

PR #1723 was closed by the author, but this feature is still missing.

### PR DESCRIPTION
**Pull request by harry-unlikelyai**
Fixes #2373

Add new BranchProtection options listed here: https://developer.github.com/v3/repos/branches/

`required_linear_history`
`allow_force_pushes`
`allow_deletions`
`lock_branch`

Replica of #1723 and #2376 but also adds `lock_branch`.

### CODE REVIEW

**Comment by martinmosegaard** [comment]
Is it possible to add `require_last_push_approval` in this PR as well?

**Comment by harry-unlikelyai** [comment]
@martinmosegaard Ok added that too now

**Comment by martinmosegaard** [comment]
Thanks! It is mentioned on https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28 fwiw.

**Comment by harry-unlikelyai** [comment]
Ah interesting, I had added it in the wrong way then since it needs to be part of the `required_pull_request_reviews` object

**Comment by treee111** [comment]
Hi @harry-unlikelyai, you have conflicts with the base branch. PR's 2793 and 2716 have also the same field `allow_deletions`, see my [comment](https://github.com/PyGithub/PyGithub/issues/2373#issuecomment-1890455669)

**Comment by EnricoMi** [comment]
Superseded by #2873, added you as co-author to appreciate your contribution.

**Pull request closed without merging**
