### PR TITLE
Export IncompletableObject in the github namespace

### PR DESCRIPTION
**Pull request by s-t-e-v-e-n-k**
When IncompletableObject was added, it was only added to
GithubException, and not imported directly into the github namespace
like other exceptions. Correct that, and clean up the resultant now
unrequired import.

### CODE REVIEW

**Comment by s-t-e-v-e-n-k** [comment]
@sfdye Where did the Travis check go? Are we planning to switch to GitHub Checks?

**Comment by sfdye** [comment]
I don’t mind switching to GH Action, if there is a working PR I can review :)

**Comment by s-t-e-v-e-n-k** [comment]
This one? :-)

**Comment by sfdye** [comment]
Maybe a separate one just for that purpose?

**Pull request merged**
