### PR TITLE
fix #1841 get_user_issues

### LINKED ISSUE #1841: Cannot get user_issues
I'm trying to fetch user_issues but this get `/issues`.

It needs to be `/user/issues`.

```
>>> import github
>>> github.enable_console_debug_logging()
>>> g = github.Github('oauth token')
>>> u = g.get_user()
>>> assert u.get_user_issues().totalCount == 3
GET https://api.github.com/issues?per_page=1 {'Authorization': 'token (oauth token removed)', 'User-Agent': 'PyGithub/Python'} None ==> 200 {'date': 'Fri, 05 Feb 2021 16:41:55 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '2', 'server': 'GitHub.com', 'cache-control': 'private, max-age=60, s-maxage=60', 'vary': 'Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding, Accept, X-Requested-With, Accept-Encoding', 'x-oauth-scopes': 'repo', 'x-accepted-oauth-scopes': '', 'x-github-media-type': 'github.v3; format=json', ...} []
```

Version 1.54.1

### PR DESCRIPTION
**Pull request by yuyan7**
fix #1841 get_user_issues

get_user_issues method is now send request to `/issues`.

fix it send request to `/user/issues`.

### CODE REVIEW

**Comment by jobveldhuis** [comment]
There seems to be [no reference](https://docs.github.com/en/rest/reference/users) to the endpoint you are calling in the Github documentation. The current endpoint of `/issues` however is mentioned and should work. Could you give me an example of code where getting issues is not working as expected?

**Comment by yuyan7** [comment]
thanks reply.

refarence is [this](https://docs.github.com/en/rest/reference/issues#list-user-account-issues-assigned-to-the-authenticated-user).

code example is #1481.

Issues that cannot be retrieved are
are from the private repository of the organization to which you belong

**Comment by jobveldhuis** [comment]
Seems like I read over that part of the GH documentation. Just tested this and it seems to work as intended, will leave a review marking it approved and hope it will be merged soon by one of the maintainers!

**Review by jobveldhuis — APPROVED** [review]

**Comment by s-t-e-v-e-n-k** [comment]
Oh my word. I'm also concerned that this doesn't fail any tests, do you feel up to adding a testcase?

**Pull request merged**
