### PR TITLE
CI: Update action actions/setup-python

### PR DESCRIPTION
**Pull request by cclauss**
https://docs.python.org/3.11/whatsnew/3.11.html
> Python 3.11 is between 10-60% faster than Python 3.10. On average, we measured a 1.25x speedup on the standard benchmark suite.

### CODE REVIEW

**Comment by trim21** [comment]
this PR is stalled…

**Comment by EnricoMi** [comment]
I think we have move to released Python3.11 already.

**Comment by trim21** [comment]
> @trim21 You mean it is not reviewed?

Then I comment, the change of this PR is already made in master branch

**Review by trim21 — APPROVED** [review]

**Review by Borda — COMMENTED** [review]
let's rename it to `update action actions/setup-python` as this does not touch python version at all

**Comment by cclauss** [comment]
> this does not touch Python version at all

Yes.  A lot has changed in the past 7 months.

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Pull request merged**
