### PR TITLE
Add support for Branch required_linear_history/allow_force_pushes/allow_deletions

### PR DESCRIPTION
**Pull request by teejae**
Add new `BranchProtection` options listed here: https://developer.github.com/v3/repos/branches/
- `required_linear_history`
- `allow_force_pushes`
- `allow_deletions`

Testing:
FYI, I could not figure out how to get the tests to run correctly

### CODE REVIEW

**Comment by s-t-e-v-e-n-k** [comment]
I'm a little confused by this -- you add the three arguments to Branch.edit, but add the methods to BranchProtection? BranchProtection is just for protection attrributes of Branch, I daresay those belong on Branch.

**Comment by s-t-e-v-e-n-k** [comment]
I understand what is going on better now -- those attributes only need to be added to BranchProtection.py (and BranchProtection.pyi).

**Comment by jacobisaliveandwell** [comment]
fixes #1716

**Comment by teejae** [comment]
@s-t-e-v-e-n-k Thanks for the review! I added to `BranchProtection.py`, but if I don't also add to the `Branch.py`, how do I edit the protection? I believe that's the right place. Can you confirm/deny?

**Review by s-t-e-v-e-n-k — CHANGES_REQUESTED** [review]
Indeed, that is looking better. The replay data needs to be fixed to support the new attributes, since you've changed what is sent, which is why the tests fail, as well as adding a test case that changes them. You'll also need to edit the Branch.pyi and BranchProtection.pyi files to add the typing hints.

**Comment by teejae** [comment]
@s-t-e-v-e-n-k thanks for the confirmation. i hadn't yet changed any code relative to the first commit.

i admit that i couldn't figure out how to generate replay data.

**Comment by s-t-e-v-e-n-k** [comment]
https://github.com/PyGithub/PyGithub/blob/master/CONTRIBUTING.md has an Automated tests section on how to do so.

**Comment by teejae** [comment]
FYI, with the github v4 graphql API now supporting these options, I no longer need this v3 API option. I had not been able to figure out how to fix the tests, even after reading the CONTRIBUTING.md file.

Closing this PR for now.

https://developer.github.com/v4/changelog/2020-11-13-schema-changes/

**Pull request closed without merging**
