### PR TITLE
Travis CI: Add flake8 tests for syntax errors and undefined names

### PR DESCRIPTION
**Pull request by cclauss**
@labrys attempted to fix these issues in #705 but those changes do not exist in the current codebase.

__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

### CODE REVIEW

**Comment by labrys** [comment]
Most of the errors my PR addressed appear to still be present in the codebase.

**Comment by labrys** [comment]
Pull request #967 should fix the majority of the Python 3 issues while leaving out opinionated fixes such as PEP8, flake and other style-related fixes.  It does not replace this PR but should fix the issues mentioned.

**Comment by labrys** [comment]
@cclauss I have come to the opinion that the PyGithub maintainers do not care about improving the code and only care to do minor patches.  Every attempt I have made to contribute to this project has ended in resounding silence.  I will no longer use PyGithub nor will I recommend it to anyone in the future due to these issues.  I will be working to remove it from all codebases I currently use it in.

**Comment by cclauss** [comment]
@labrys #1027 explains why the current code working on both Python 2 and Python 3 but it relies on a setuptools "feature" that no longer recommended.

**Comment by labrys** [comment]
@cclauss I am fully aware of how this "works" but its also a likely cause of several of the issues that have remained unaddressed.  Additionally I already did the work that #1027 addresses along with all the other Python 3 compatibility issues in PR #967 making the code fully Python 2/3 compatible.  It is the second time I have attempted to provide these code fixes to the code base and the PRs have been ignored without comment.  As I stated I will no longer be using PyGithub nor wasting my time trying to provide upstream fixes.

**Comment by cclauss** [comment]
Understood.  I did read through #967 before I started today's PRs.  I understand that they are mostly subsets of 967 but I have found that often maintainers are reluctant to merge large PRs that touch many files.  Let's see if there is forward progress with these smaller PRs.

**Comment by labrys** [comment]
@cclauss I'm fully aware that a maintainer can be reluctant to merge large PRs.  A courtesy note to the contributor to that effect shows that the effort isn't ignored.  This is the second time an attempt to fix these issues was ignored without comment.  Four months without a single comment on a PR (e.g. #705) is ignoring it.  Additionally PR #979 also sat ignored until today and is not large by any stretch of the imagination.

**Pull request closed without merging**
