### PR TITLE
Implement ProjectCard.delete()

### PR DESCRIPTION
**Pull request by s-t-e-v-e-n-k**
To work towards implementing more of the API surrounding Project Cards,
add a delete method. With thanks to Christopher Mitchell, Ph.D.

Fixes #1409

### CODE REVIEW

**Comment by s-t-e-v-e-n-k** [comment]
@sfdye Gah, now I can't land my own changes, this is terrible!

**Comment by sfdye** [comment]
The gist is any PR must be looked at one least one other person before merging

**Comment by s-t-e-v-e-n-k** [comment]
@sfdye I've been landing my own fixes for a while, it's a tough habit to break. :-)

**Comment by sfdye** [comment]
Yeah I know, it’s just we all are human and human make mistakes, having one extra eye to check will reduce the bugs accidentally merged into master.

**Pull request merged**
