### PR TITLE
add ldap_dn attribute for teams, as described in https://developer.gi…

### PR DESCRIPTION
**Pull request by schlitzered**
add ldap_dn attribute for the /org/{org}/teams endpoint as documented here:

https://developer.github.com/enterprise/2.21/v3/teams/#create-a-team

### CODE REVIEW

**Comment by schlitzered** [comment]
the change is working with the github enterprise version we have at our company, i just tested this locally

**Comment by s-t-e-v-e-n-k** [comment]
But we do need at least three test cases changed, likely with mocked test data.

**Comment by schlitzered** [comment]
i am not sure what exactly is expected, if you could advice, i can take a look.

**Comment by schlitzered** [comment]
@s-t-e-v-e-n-k: would you be able to give me some hints on what is expected to change? so we can get this complaint and merged?

**Comment by s-t-e-v-e-n-k** [comment]
There are a bunch of unit tests for each of the objects -- you need to add a check for the attribute to tests/Team.py , along with probably adding to the replay data so the the attribute is populated.

**Comment by schlitzered** [comment]
i added/updated tests for the ldap_dn attribute. can you please take a look?

the tests run successfull locally, no clue why the "CI / test (Python 3.6) (pull_request) Failing after 2m — test (Python 3.6) " test failed

**Comment by schlitzered** [comment]
hi, is there still anything open that needs to be adjusted?

**Comment by s-t-e-v-e-n-k** [comment]
The 'lint' test is failing, which enforces our code style -- `tox -elint` and inspect the changes and then push them.

**Comment by schlitzered** [comment]
style changes have been implemented

**Comment by schlitzered** [comment]
@s-t-e-v-e-n-k ping

**Comment by schlitzered** [comment]
@s-t-e-v-e-n-k can you please have a look at this? please let me know if something is missing

**Pull request closed without merging**
