### PR TITLE
Drop support for Python 3.5

### PR DESCRIPTION
**Pull request by s-t-e-v-e-n-k**
In preperation for starting to use 3.6+ only features, stop testing
Python 3.5 in our CI, and bump our minimum required version.

### CODE REVIEW

**Review by sfdye — APPROVED** [review]

**Comment by sfdye** [comment]
What py36+ feature?

**Comment by s-t-e-v-e-n-k** [comment]
https://www.python.org/dev/peps/pep-0498/ is the big one

**Comment by sfdye** [comment]
I love f-string

**Comment by s-t-e-v-e-n-k** [comment]
I am looking forward to covering this code base in them. :-)

**Pull request merged**
