### PR TITLE
Add `generate_release_notes` parameter to `create_git_release` and `create_git_tag_and_release`

### LINKED ISSUE #2383: `create_git_release` lacks the `generate_release_notes` parameter
[`create_git_release`](https://github.com/PyGithub/PyGithub/blob/master/github/Repository.py#:~:text=def%20create_git_release) lacks the `generate_release_notes` parameter specified in [GitHub API reference](https://github.com/PyGithub/PyGithub/blob/master/github/Repository.py#:~:text=def%20create_git_release). Since it's common to create a release with autogenerated release notes, adding the boolean parameter to `create_git_release` function seems to be a meaningful life improvement for PyGithub users (We want to use it ourselves in one project).

### PR DESCRIPTION
**Pull request by WojciechBarczynski**
Added `generate_release_notes` parameter to `create_git_release` and `create_git_tag_and_release`.

Fixes #2383.

### CODE REVIEW

**Comment by WojciechBarczynski** [comment]
Can someone review this?

**Comment by maingoh** [comment]
Small suggestion, adding support for `notes-start-tag` like in https://cli.github.com/manual/gh_release_create ?

**Review by mjia-tripactions — APPROVED** [review]

**Comment by WojciechBarczynski** [comment]
@EnricoMi Can you check this out?

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Comment by EnricoMi** [comment]
@maingoh looks like you want something like #2110.

**Comment by maingoh** [comment]
I would like to be able to set `notes-start-tag` when generating the release notes otherwise the changelog generated is based on the diff with the latest release tag. Sometimes we want to generate it based on another tag.

**Pull request merged**
