### PR TITLE
Add ability to check combined status.

### PR DESCRIPTION
**Pull request by doctoryes**
Adds:
  - CommitCombinedStatus class
  - get_combined_status() to Commit class to return combined status

### CODE REVIEW

**Comment by feanil** [comment]
@jzelinskie can you take a look at this change please? Is there anything more it needs before it can be merged?

**Comment by jzelinskie** [comment]
This looks good, it just could use a test!

**Comment by doctoryes** [comment]
@jzelinskie Test is in!

**Comment by jzelinskie** [comment]
LGTM! Thanks for the contribution!

**Pull request merged**
