### PR TITLE
Add support for releases

### PR DESCRIPTION
**Pull request by edhollandAL**
This pull request adds support for getting + creating releases from tags. I have not added support for uploading assets to these releases as we do not currently require this functionality.

### CODE REVIEW

**Comment by jzelinskie** [comment]
Nice! Looks really good at first glance. Since this is a pretty big change, I'll wait for another maintainer to take another look before merging.

**Comment by edhollandAL** [comment]
Brill! Thanks for the feedback :)

**Comment by edhollandAL** [comment]
@jzelinskie: Is there anyone else you had in mind to review these changes?

Thanks

Ed

**Comment by jzelinskie** [comment]
No one specific, but lgtm so I'm merging.

**Comment by edhollandAL** [comment]
Great stuff! Thanks.

Do you think it would be worthwhile making this an official release + updating pip as well?

Ed

**Comment by jzelinskie** [comment]
@edhollandAL I would like to do a release, but I first need to merge develop and master -- which have actually diverged a bit. I'm a bit swamped on work, so I cannot promise when that would happen. There are other maintainers who may have some time, but once again, I cannot make any promises.

**Comment by edhollandAL** [comment]
Hi,

I’ve merged in my own fork + created https://github.com/PyGithub/PyGithub/pull/315 to merge back into the master repo. The merge looks good to me (maybe missing some tests in an ideal world), but probably makes sense if someone with more experience of the code base has another look.

Hope this helps

Ed

**Pull request merged**
