### PR TITLE
issue: add lock/unlock

### PR DESCRIPTION
**Pull request by FFY00**

### CODE REVIEW

**Comment by sfdye** [comment]
Hi @FFY00 Thank you very much for your PR. It would be helpful if you can add a unit test. You can refer to the contribution [docs](https://github.com/PyGithub/PyGithub/blob/master/CONTRIBUTING.md#adding-missing-attributes-for-a-githubobject) for instructions.

**Comment by FFY00** [comment]
Do you have any script to had the replay data or do I have to add it manually?

**Comment by sfdye** [comment]
It's in the link above

**Comment by FFY00** [comment]
Yeah, but I am not adding attributes. I am adding functions.

**Comment by sfdye** [comment]
Sorry wrong anchor point:
https://github.com/PyGithub/PyGithub/blob/master/CONTRIBUTING.md#automated-tests

**Comment by FFY00** [comment]
I am getting an error saying the issue was not found. I get the same from other tests.

```
======================================================================
ERROR: testLock (tests.Issue.Issue)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/Issue.py", line 44, in setUp
    self.issue = self.repo.get_issue(28)
  File "github/Repository.py", line 1990, in get_issue
    self.url + "/issues/" + str(number)
  File "github/Requester.py", line 275, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "github/Requester.py", line 286, in __check
    raise self.__createException(status, responseHeaders, output)
UnknownObjectException: 404 {u'documentation_url': u'https://developer.github.com/v3/issues/#get-a-single-issue', u'message': u'Not Found'}

----------------------------------------------------------------------
```

**Pull request merged**
