### PR TITLE
Get a project column by id

### PR DESCRIPTION
**Pull request by FlorentClarret**
This PR resolves the https://github.com/PyGithub/PyGithub/issues/1057
I also added some tests for the ProjectColumn class

### CODE REVIEW

**Comment by FlorentClarret** [comment]
I just noticed that other ProjectColumn related methods are missing like update and delete. @sfdye do you think we should keep adding those methods to the main class or we can add them somewhere else to avoid putting everything in the main class? As static method to the ProjectColumn class maybe?

**Comment by sfdye** [comment]
Let’s add to the main for now. Will revisit the refactoring later. 

cc @s-t-e-v-e-n-k

**Comment by s-t-e-v-e-n-k** [comment]
ProjectColumn should match ProjectCard -- I think the delete() and edit() methods would be incredibly similar.

**Comment by FlorentClarret** [comment]
Oh my bad, I didn't see them, you're right. I will add them in another PR

**Comment by FlorentClarret** [comment]
Thanks for the review ! If you want me to add something else to this PR, please tell me ;)

**Pull request merged**
