### PR TITLE
Add support for repository autolink references

### LINKED ISSUE #1293: Support for "Autolink References" (aka key_links)
## Story
As a user of this fine library, I'd like to be able to conduct CRUD operations on the new _Autolink References_ feature, [introduced 2019-10-14](https://github.blog/2019-10-14-introducing-autolink-references/). This would allow for creating automation, such as a [probot](https://github.com/probot) app for managing them.

Unfortunately though, there is no real API target yet and only works through `github.com` -- there is not even a [preview](https://developer.github.com/v3/previews/) for it. Perhaps given that, this feature request should be considered void until they do.

## Details
Using browser dev tools, we can see what the requests look like. Below are the observations I made.

### Check (POST) `/:owner/:repo/settings/key_links/check`
Multipart Form Fields:
- `key_link[key_prefix]`: `JIRAPROJECTA-`
- `key_link[url_template]`: `https://jira.pygithub.com/browse/JIRAPROJECTA-<num>`

### Create (POST) `/:owner/:repo/settings/key_links/new`
Form fields:
- `utf8`: `✓` _No idea what this is about..._
- `authenticity_token`: _REDACTED (string, base64 encoded binary string)_
- `timestamp`: _REDACTED (long, unix epoch of request with millis)_
- `timestamp_secret`: _REDACTED (string, 64 character hexadecimal)_
- `key_link[key_prefix]`: `JIRAPROJECTA-`
- `key_link[url_template]`: `https://jira.pygithub.com/browse/JIRAPROJECTA-<num>`

### Delete (POST) `/:owner/:repo/settings/key_links/<key_link_id>`
Form fields:
- `_method`: `delete`
- `authenticity_token`: _REDACTED (string, base64 encoded binary string)_

### List
This one doesn't seem to have a REST-y endpoint yet and reloads the page with
a (GET) `/:owner/:repo/settings/key_links`.

### PR DESCRIPTION
**Pull request by theCapypara**
Adds support for repository autolinks. I put this on draft, since the API for it is beta and subject to change.

This will (actually :) ) close #1293.

### CODE REVIEW

**Comment by theCapypara** [comment]
As far as I can tell a custom Accept header is not needed.

**Comment by s-t-e-v-e-n-k** [comment]
https://github.com/PyGithub/PyGithub/blob/master/CONTRIBUTING.md#automated-tests

**Comment by theCapypara** [comment]
I can't record replay data since it changes the Repository.setUp replay data to my fork, which makes all the other tests fail. I can't record data using the main repository, since I don't have write access.

**Comment by theCapypara** [comment]
I guess I *could* change the test case to use my fork only for these methods? But that doesn't really sound like a great solution.

**Comment by theCapypara** [comment]
I could also manually change the replay data (replace mentions of my fork with the main repo) I guess, if that's okay.

**Comment by theCapypara** [comment]
Done. I also undrafted since I'm fairly optimistic this API is stable enough / even if they end up changing something after "Beta" we can just adjust the code again.

**Comment by theCapypara** [comment]
& rebased for good meassure

**Comment by theCapypara** [comment]
@s-t-e-v-e-n-k Do you have an update on the review status?

**Comment by theCapypara** [comment]
@s-t-e-v-e-n-k Can you re-open this?

**Comment by megamorf** [comment]
Can we please re-open this ticket and get the code merged. We're in need of the feature and it'd be better to have it as part of PyGithub instead of having to use a custom implementation.

**Comment by megamorf** [comment]
@sfdye Can we get this feature into the next release? It would be a waste to throw away all the work that already went into it.

**Comment by sfdye** [comment]
Re-opened, if someone could resolve the conflicts I will review

**Comment by theCapypara** [comment]
Done.

**Comment by megamorf** [comment]
> Done.

Looks like one of the CI tests failed. And upon closer inspection it seems that the code needs to be formatted by black to pass the lint check and the import order needs to be updated.

black: https://github.com/PyGithub/PyGithub/actions/runs/3344110825/jobs/5538083016#step:5:39
isort: https://github.com/PyGithub/PyGithub/actions/runs/3344110825/jobs/5538083016#step:5:52

Both should be fixed by running the pre-commit hook on the PR branch.

**Review by sfdye — APPROVED** [review]

**Pull request merged**
