### PR TITLE
user.node_id missing

### PR DESCRIPTION
**Pull request by suryasr007**
'node_id' attribute was missing. Hence added the attribute using add_attribute script in AuthorizedUser  and NamedUser classes. 
This fixes issue #999 .

### CODE REVIEW

**Comment by s-t-e-v-e-n-k** [comment]
Needs a test for the new attribute, make sure "node_id" is in the replay data for the NamedUser.testAttributesOfSelf and AuthenticatedUser.testAttributes tests, and assert the value in the test functions. I'm happy to give more concrete help if required.

**Comment by suryasr007** [comment]
@s-t-e-v-e-n-k I am confused whether to create to a new test file with issue number **or** simply add the "node_id" to AuthenticatedUser.py and NamedUser.py tests.

**Comment by suryasr007** [comment]
> @s-t-e-v-e-n-k 

Thanks for the help. I am confused whether to create to a new test file with issue number **or** simply add the "node_id" to AuthenticatedUser.py and NamedUser.py tests.

**Comment by suryasr007** [comment]
@s-t-e-v-e-n-k 

Thanks for the help. I have added the tests.

**Comment by suryasr007** [comment]
@s-t-e-v-e-n-k 

Any update on PR?

**Comment by s-t-e-v-e-n-k** [comment]
Looks fine to me, but I can't merge it. @sfdye what do you think of this change?

**Pull request merged**
