### PR TITLE
Type stubs for mypy

### PR DESCRIPTION
**Pull request by zer0tonin**
Adds type stubs that can be used in mypy, as requested in: #1217
The current type stubs were generated by MonkeyType against the unit test, however it missed a few things here and there so manual fix is required before merging (still WIP).

### CODE REVIEW

**Comment by trickeydan** [comment]
Typestub files have extension `.pyi`, not `.piy`.

See https://mypy.readthedocs.io/en/latest/stubs.html for more details on stubs :)

**Comment by zer0tonin** [comment]
> Typestub files have extension `.pyi`, not `.piy`.

Weird that mypy didn't warn me about that when testing lol

**Comment by Richard-Lynch** [comment]
Hey, I was using the module recently and was going to add types anyway, and then came across this! 

Is there any way that the PaginatedList class could be made generic, and then narrowed when it’s returned so the values pulled from it are also typed? 

I’ll follow up with examples if needed tomorrow.

**Comment by zer0tonin** [comment]
I'm really not sure if generics can work only with stubs @Richard-Lynch 
In any case, I think it's a good idea, but maybe it should be done as "step 2".

**Comment by Richard-Lynch** [comment]
I actually didn't realise that, my bad! 

I'll keep an eye for step 2, is there an issue I can watch for the depreciation of Py2 support?

**Comment by sfdye** [comment]
Let me know when this is ready for review :)

**Comment by zer0tonin** [comment]
I still need to go over 2/3 classes, and apply the changes you recently made to membership. Shouldn't take too long tho.

**Comment by zer0tonin** [comment]
@sfdye I went over every class by hand, things are good for me. I think you can review now. :slightly_smiling_face:

**Comment by JLLeitschuh** [comment]
Can't these be included inline now since Python 2 support has been dropped?

**Comment by sfdye** [comment]
It could. We just need to resolve the conflicts first. 

@zer0tonin Thank you for the hard work. Could you add a simple tutorial of how to add type stub for new classes and methods? It should be part of the contributing guide so that we won't constantly get out of date.

**Comment by zer0tonin** [comment]
@sfdye sure I will try to do add that to contributing.md when I have the time. Probably next week.

**Comment by sfdye** [comment]
@zer0tonin Do you have any time to look at this again?

**Comment by trickeydan** [comment]
> Could you add a simple tutorial of how to add type stub for new classes and methods? It should be part of the contributing guide so that we won't constantly get out of date.

What is the issue with the [official tutorial] (https://mypy.readthedocs.io/en/stable/stubs.html)? 

I see little point in duplicating information, and then having to update it, rather than just linking to the upstream docs.

**Comment by sfdye** [comment]
@trickeydan linking official docs would be useful, however I couldn't find anything touching how to keep stubs up-to-date with the always changing source code. Perhaps via a pre-commit plugin? Maybe even adding CI job to check for missing stubs?

**Comment by christopher-dG** [comment]
Sorry to butt in (I've been eagerly waiting for this PR to land), but I always run mypy as part of CI pipelines. [This Hacker News article and thread has some good info.](https://news.ycombinator.com/item?id=22302789)

**Comment by sfdye** [comment]
Actually we could re-apply stubs to original source code and run mypy at CI

**Comment by sfdye** [comment]
I've rebased changes from master and resolved the conflicts. However Travis is having issue, hopefully it will be green afterwards so we can get this merged 🤞

**Comment by s-t-e-v-e-n-k** [comment]
This is missing new classes that have been added in the meantime, but I have no objections to landing it now (and adding them afterwards) if Travis can stop having issues.

**Comment by sfdye** [comment]
@zer0tonin I've merged this PR upon CI becomeing green :) Thanks for the huge effort for making PyGithub static typed. Just so can reproduce the set-up in the future, could you share the monkeytype config you used when generating the stubs?

**Pull request merged**
