### PR TITLE
CI: drop precommit job, use bot, move docs into CI workflow

### PR DESCRIPTION
**Pull request by Borda**
Moving docs build to CI checks as this is not much lint but real check
Also, I may suggest installing recommit [bot](https://precommit.ci/) instead of GH action which has the advantage of eventually automatically fixing open PRs

cc: @EnricoMi

### CODE REVIEW

**Comment by Borda** [comment]
@sfdye @EnricoMi could you pls have look / review :flamingo:

**Comment by EnricoMi** [comment]
I am fine with moving docs to CI. Can you elaborate on the automatically fixing PRs bit?

**Comment by Borda** [comment]
> I am fine with moving docs to CI. Can you elaborate on the automatically fixing PRs bit?

if you install this bot (https://pre-commit.ci/) for org or just this repo it will automatically run recommit as configured within this repo and if the recommit generates any changes, it will be append as commit to the particular PR

**Comment by EnricoMi** [comment]
And this happens monthly?

      autoupdate_schedule: 'monthly'

**Comment by Borda** [comment]
> And this happens monthly?
> 
> ```
>   autoupdate_schedule: 'monthly'
> ```

This means that every month bump hooks versions to the latest (via PR) or you can set weekly or quarterly... if you have all latest, no PR is created

**Comment by Borda** [comment]
@EnricoMi may we proceed with this update? 🐿️

**Comment by sfdye** [comment]
No objection, let's do this

**Review by EnricoMi — CHANGES_REQUESTED** [review]
Can we not rename `ci.yml` file?

**Comment by Borda** [comment]
> Can we not rename `ci.yml` file?

reverted

**Comment by EnricoMi** [comment]
> No objection, let's do this

@sfdye you need to install this Github app: https://github.com/marketplace/pre-commit-ci

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Comment by Borda** [comment]
> LGTM!

cool, lets first install the bot :flags:

**Comment by Borda** [comment]
@sfdye friendly reminder... :flamingo:

**Comment by Borda** [comment]
@EnricoMi is there anything I can do to help it land? 🦩

**Comment by EnricoMi** [comment]
Nope, nothing we can do.

**Comment by Borda** [comment]
@EnricoMi, shall we close this PR in such a case?

**Comment by Borda** [comment]
> @EnricoMi, shall we close this PR in such a case?

ok, let's close it... 😿

**Pull request closed without merging**
