### PR TITLE
Add oauth authentication

### PR DESCRIPTION
**Pull request by maria**
Hi,

I implemented this, and I would like to make it better so that we can integrate it in the package.
I would like your feedback.

I used these methods to authenticate and they work.

Thanks!

TODOs:
- [ ] Get feedback about naming/style
- [ ] Write tests
- [ ] Update the class

### CODE REVIEW

**Comment by jzelinskie** [comment]
Hi @maria, it's been a long time and I was curious about the state of this PR.

**Comment by maria** [comment]
@jzelinskie Hi, I will take a look on it and maybe we can merge it soon.

**Comment by maria** [comment]
@jzelinskie Can you help me by guiding me with the tests, please? For example, how this [file](https://github.com/maria/PyGithub/blob/add-oauth-authentication/github/tests/ReplayData/OAuth.testGetAccessToken.txt) should be structured?

**Comment by jzelinskie** [comment]
@maria, you can find the the meaning of the individual lines [here](https://github.com/maria/PyGithub/blob/6a7425703917be7ae09c5d10b8157700fa9b36b4/github/tests/Framework.py#L145-L151). Most information can be extrapolated from that file. However, we should probably have a README in the tests dir that explains this.

**Comment by maria** [comment]
@jzelinskie Hi, can you help me finish this PR. I added some tests, and from the file you gave I haven't understood much. Thanks!

**Comment by maria** [comment]
@sfdye I think is best to close it, is super deprecated - a new one would be better. Thanks

**Comment by sfdye** [comment]
@maria Sure, sorry for the super delayed response.

Feel free to open a new one, I will be happy to do a quick review 😄

**Pull request closed without merging**
