### PR TITLE
Add myself to MAINTAINERS

### PR DESCRIPTION
**Pull request by trim21**

### CODE REVIEW

**Comment by trim21** [comment]
@sfdye @s-t-e-v-e-n-k @EnricoMi @JLLeitschuh

**Comment by EnricoMi** [comment]
@JLLeitschuh and me are only Collaborators, we do not have the permissions to assign maintainers. Adding users to the `MAINTAINERS` file does not grant permissions in Github.

**Comment by trim21** [comment]
> @JLLeitschuh and me are only Collaborators, we do not have the permissions to assign maintainers. Adding users to the `MAINTAINERS` file does not grant permissions in Github.

OK， I'm hoping the other 2 maintainers can grant me permission.

**Comment by trim21** [comment]
@sfdye @s-t-e-v-e-n-k

**Comment by trim21** [comment]
@sfdye @s-t-e-v-e-n-k

**Comment by trim21** [comment]
@sfdye @s-t-e-v-e-n-k please

**Comment by EnricoMi** [comment]
@trim21 thanks for your contributions to the CI and code style so far. I think, contributing some features or reviewing others' pull requests will show owners of this project how thorough and considerate you are working for the benefit of this project. That should help getting you added.

**Pull request closed without merging**
