### PR TITLE
Fix add_to_watched for AuthenticatedUser

### PR DESCRIPTION
**Pull request by bryanhuntesl**
The functionality was completely broken - api endpoints were wrong/didn't work. Tested by logging in as an authenticated user - verified listing watches, add watch, and remove watch.

### CODE REVIEW

**Comment by bryanhuntesl** [comment]
Unit tests are working now, unfortunately Travis seems to be down at the moment - maybe someone could kick off a build ?

**Comment by bryanhuntesl** [comment]
Travis successfully built off my fork - https://travis-ci.org/bryanhuntesl/PyGithub/builds/348309268

**Comment by sfdye** [comment]
@bryanhuntesl Thank you so much for your contribution.

**Comment by bryanhuntesl** [comment]
My pleasure

**Pull request merged**
