### PR TITLE
Allow for cancellation of organization invitations

### PR DESCRIPTION
**Pull request by jsimpso**
This pull request will implement a new function `cancel_invitation` for `github.Organization` objects, allowing for cancellation of organization invitations per https://docs.github.com/en/rest/reference/orgs#cancel-an-organization-invitation

```python
>>> pending_invitations = github_org.invitations()
>>> any([i for i in pending_invitations if i.email == 'user@example.com'])
False
>>> github_org.invite_user(email='james@snowterminal.com')
>>> pending_invitations = github_org.invitations()
>>> any([i for i in pending_invitations if i.email == 'user@example.com'])
True
>>> pending_invitation = [i for i in pending_invitations if i.email == 'user@example.com'][0]
>>> github_org.cancel_invitation(pending_invitation)
>>> pending_invitations = github_org.invitations()
>>> any([i for i in pending_invitations if i.email == 'user@example.com'])
False
```

### CODE REVIEW

**Comment by s-t-e-v-e-n-k** [comment]
The test failures in AuthenticatedUser are my partially fault -- I pushed a fix a few minutes ago, please rebase.

WRT type checking, I actually mean type hints, and picking on the method before the you added, like this: https://github.com/PyGithub/PyGithub/blob/master/github/Organization.pyi#L164

As as aside, you can just assertTrue() with calling the method in the test case, no need for a result variable.

**Comment by jsimpso** [comment]
> More issues caused by master, sorry, rebase, and we should be good to merge.

Done, fingers crossed :)

**Comment by MaximKorobovAtTinkoff** [comment]
@s-t-e-v-e-n-k, when do you plan to release 1.56 with this update?
Seems like 1.55 was in April 26, 2021 and current PR was merged later. So no new functionality available when installed pip package.

**Comment by MaximKorobovAtTinkoff** [comment]
Temporary patch that works for those who need that functionality immediately:
```
def cancel_invitation(self, invitee):
    """
    :calls: `DELETE /orgs/{org}/invitations/{invitation_id} <https://docs.github.com/en/rest/reference/orgs#cancel-an-organization-invitation>`_
    :param invitee: :class:`github.NamedUser.NamedUser`
    :rtype: None
    """
    assert isinstance(invitee, NamedUser.NamedUser), invitee
    status, headers, data = self._requester.requestJson(
        "DELETE", f"{self.url}/invitations/{invitee.id}"
    )
    return status == 204

...

    org.cancel_invitation = types.MethodType(cancel_invitation, org)

    org.cancel_invitation(invite)
```



This manual was used: https://bobbyhadz.com/blog/python-add-method-to-existing-object

**Pull request merged**
