### PR TITLE
Support Environment Variables and Secrets

### PR DESCRIPTION
**Pull request by AndrewJDawes**
Adds support for creating, listing, updating, and deleting Repository Environment [Variables](https://docs.github.com/en/rest/actions/variables?apiVersion=2022-11-28#list-environment-variables) and [Secrets](https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#list-environment-secrets).

- Utilizes existing `github.Variable.Variable` and `github.Secret.Secret` models
- Adds methods to existing `github.Environment.Environment` model to interact with the Environment's Variables and Secrets.

Tests can be found here:

- `tests/Environment.py::Environment::testEnvironmentVariable`
- `tests/Environment.py::Environment::testEnvironmentVariables`
- `tests/Environment.py::Environment::testEnvironmentSecret`
- `tests/Environment.py::Environment::testEnvironmentSecrets`

The tests also provide a good demo of the new functionality and how to test it.

Fixes: #2067

Depends on: #2835

### CODE REVIEW

**Comment by EnricoMi** [comment]
#2835 merged, please rebase

**Comment by AndrewJDawes** [comment]
@EnricoMi - rebased! Let me know if there's anything else I can help with to get these merged!

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Comment by sfc-gh-hpathak** [comment]
This is great.. when will this be released?

**Pull request merged**
