### PR TITLE
PullRequest.update_branch(): allow expected_head_sha to be empty

### PR DESCRIPTION
**Pull request by ahauan4**
See issue [https://github.com/PyGithub/PyGithub/issues/1411](1411)

The function `PullRequest.update_branch()` currently requires parameter `expected_head_sha`.
But this parameter is not mandatory according to
https://developer.github.com/v3/pulls/#update-a-pull-request-branch
> Default: SHA of the pull request's current HEAD ref.

This pull request makes the parameter optional

### CODE REVIEW

**Comment by s-t-e-v-e-n-k** [comment]
Would you mind also adding a new test case calling the function with no arguments? Other than that, this looks great.

**Comment by ahauan4** [comment]
I will try to do this

**Comment by ahauan4** [comment]
@s-t-e-v-e-n-k  I added the test but it fails. When I test it with our GitHub Enterprise server it works. Is this a Enterprise-only feature? Our Github Enterprise Server runs version 2.19.4

**Comment by s-t-e-v-e-n-k** [comment]
The test failure is due to not having an API call in the replay data -- the unit tests call functions which result in HTTPS requests which are replayed by reading from the replay data, you'll have to update the relevant replay data as well.

**Comment by ahauan4** [comment]
@s-t-e-v-e-n-k I tried to do this according to the contribution guideline (https://github.com/PyGithub/PyGithub/blob/master/CONTRIBUTING.md#automated-tests), but it does not seem to work.
I created a `GithubCredentials.py` file with my Github username and password and called `python -m tests PullRequest.testUpdateBranch --record` but I get the following error:

```
C:\Github\PyGithub\github\Requester.py:563: ResourceWarning: unclosed <ssl.SSLSocket fd=712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('...', 55066), raddr=('140.82.118.6', 443)>
  self.__connection = self.__connectionClass(
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Github\PyGithub\github\Requester.py:563: ResourceWarning: unclosed <ssl.SSLSocket fd=444, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('...', 55067), raddr=('140.82.118.6', 443)>
  self.__connection = self.__connectionClass(
ResourceWarning: Enable tracemalloc to get the object allocation traceback
E
======================================================================
ERROR: testUpdateBranch (tests.PullRequest.PullRequest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Github\PyGithub\tests\PullRequest.py", line 43, in setUp
    self.pull = self.repo.get_pull(31)
  File "C:\Github\PyGithub\github\Repository.py", line 2483, in get_pull
    headers, data = self._requester.requestJsonAndCheck(
  File "C:\Github\PyGithub\github\Requester.py", line 317, in requestJsonAndCheck
    return self.__check(
  File "C:\Github\PyGithub\github\Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://developer.github.com/v3/pulls/#get-a-single-pull-request"}

----------------------------------------------------------------------
Ran 1 test in 1.298s

FAILED (errors=1)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='C:\\Github\\PyGithub\\tests\\ReplayData\\PullRequest.setUp.txt' mode='w' encoding='utf-8'>
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=452, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('...', 55068), raddr=('140.82.118.6', 443)>
```

Can you tell me what I did wrong or can you maybe do it by yourself, since I'm not familiar with this test suite?

**Comment by s-t-e-v-e-n-k** [comment]
That is because there isn't a PR numbered 31 on Github itself, but other than that, your set up is correct, since you can make requests to Github. For PullRequest and other test classes that have a lot of historical baggage like that I tend to generate the replay data by hand using pdb. What you can do is change the setUp() method to grab a PR that does exist, but disable every other test in the class.

**Comment by ahauan4** [comment]
@s-t-e-v-e-n-k Ok I figured it out and edited the replay file manually. The test seems to pass now.
There's still one test failing. Do you know what the problem might be?

**Comment by ahauan4** [comment]
@s-t-e-v-e-n-k All tests have passed now. I got tox running with Python 3.8 which I'm using.
Please review again.

**Comment by s-t-e-v-e-n-k** [comment]
@ahauan4 Thanks!

**Pull request merged**
