### PR TITLE
Added missing params to constructor when reversed

### LINKED ISSUE #945: PaginatedList reversed property loses http headers
In reversed(), 'headers' parameter is not passed to PaginatedList(). It makes some APIs not reversible. For example, get_stargazers_with_dates() which requires "Accept: application/vnd.github.v3.star+json" header in the API call.

### PR DESCRIPTION
**Pull request by netsgnut**
This PR proposes adding two missing params to constructor in `.reversed`. This preserves the `headers` as well as the `list_item` once cloned.

Fixes #945.

### CODE REVIEW

**Comment by sfdye** [comment]
A unit test would be nice, as this change has a rather large impact.

**Comment by netsgnut** [comment]
@sfdye Indeed.

Would adding a `github/test/Issue945.py` with tests that assert a `reversed` `PaginatedList` to share the `headers` and `list_item` as the original be sufficient?

**Comment by sfdye** [comment]
Yes as long as it can demonstrate the original header does not get lost.

**Comment by netsgnut** [comment]
Thanks @sfdye. I have added a new test file for that. Hope that covers what we should.

**Comment by sfdye** [comment]
@netsgnut Thank you for your PR!

**Comment by kelvinwonghk01** [comment]
@sfdye Thank you (and the whole maintainer team) for the project! :)

**Comment by netsgnut** [comment]
@sfdye Pleasure is mine. Thank you all for this project ;)

**Pull request merged**
