### PR TITLE
Support multiple assignees on Issue & PullRequest

### PR DESCRIPTION
**Pull request by tmshn**
### The problem so far

As reported in #404 and #439, the Github official API now supports multiple assignees (along with Enterprise edition since v2.7).
However, PyGithub doesn't support it yet.

### How it's solved

1. Added the `assignees` attribute to the `Issue` object (e0e5fdf9c06be34d580aeca4829e7d53757bce89)
    - In older version of API which doesn't support multiple assignees, `Issue.assignees` returns just a single-element list of `Issue.assignee`.
2. Enhance support of `assignees` argument in `Issue.edit()` (14dd9f0850f4f280fd7bdb354860c88c5ca7356b)
    - Some work have done in #466 already, but it now accepts a list of `github.Nameduser.NamedUser`.
3. Added `assignees` argument in `Repository.create_issue()` (ba007dc8a8bb5d5fdf75706db84dab6a69929d7d)
4. Added the `assignees` attribute also to the `PullRequest` object. (c0de6be5ea7d285f110ba82bb96bf6fe80b01945)
    - Following the [comment](https://github.com/PyGithub/PyGithub/pull/469#issuecomment-261708142) from @andrzejchm, added the `assignees` attribute to `PullRequest` object as well. The diff is same as the first commit.
5. Added the `add_to_assignees` and the `remove_from_assignees` methods to the `Issue` object. (66430d7831aa31beb726efa4a3ea25f2c7950819)
    - Following the [comment](https://github.com/PyGithub/PyGithub/pull/469#issuecomment-262274782) from @mgorny, added the `add_to_assignees` and the `remove_from_assignees` methods to the `Issue` object, each of which utilizes [the "add assignees to an issue" API](https://developer.github.com/v3/issues/assignees/#add-assignees-to-an-issue) API and [the "remove assignees from an issue" API](https://developer.github.com/v3/issues/assignees/#remove-assignees-from-an-issue) respectively.
    - These methods are to modify assignees on an issue without changing the existing assignees. To set assignees ignoring the existing assignees or to clear all assignees, use `edit` method like `issue.edit(assignees=['user1', 'user2'])` or `issue.edit(assignees=[])`.

### Note for maintainers

All of the `ReplayData` is edited manually by my hand, since I could not edit issues on this repo.
If that is problematic, feel free to overwrite them!

### CODE REVIEW

**Comment by andrzejchm** [comment]
awesome! I'd love it to be added to `PullRequest`  aswell :)

**Comment by tmshn** [comment]
@andrzejchm Yay, I've done it! 👊

**Comment by mgorny** [comment]
Could you also add `add_to_assignees` and `delete_assignees` (alike the funcs for labels) using https://developer.github.com/v3/issues/assignees/ ? The two other methods would also be useful for me.

**Comment by tmshn** [comment]
@mgorny Sure! Could you wait until weekend? 😎

**Comment by mgorny** [comment]
Sure, thanks a lot!

**Comment by tmshn** [comment]
@mgorny Added 👍 
Actually, Github API does NOT have a method to "delete" (i.e, "clear all") assignees unlike they have it for labels. Thus, I didn't add `delete_assignees` method. As I wrote above, use `issue.edit(assignees=[])` to clear all assignees.

**Pull request merged**
