### PR TITLE
Adding delete_review function

### PR DESCRIPTION
**Pull request by sameer1996-cmd**

### CODE REVIEW

**Review by sameer1996-cmd — COMMENTED** [review]
Not correct, file updated in the next commit

**Review by sameer1996-cmd — COMMENTED** [review]
Added a delete_review function and changed the event default value to blank instead of 'COMMENT'

**Review by sameer1996-cmd — COMMENTED** [review]
.

**Comment by s-t-e-v-e-n-k** [comment]
Thank you for your work, but please push up one pull request for this, and I'll review that.

**Pull request closed without merging**
