### PR TITLE
Add missing attributes to Branch

### PR DESCRIPTION
**Pull request by kang-makes**
Hi!

We added a bunch of missing attributes missing in `Branch.py` that are needed for a project we own.

I tried my best to follow the [CONTRIBUTING.md](https://github.com/PyGithub/PyGithub/blob/master/CONTRIBUTING.md) guide but I was not able to follow the [Adding missing attributes for a GithubObject](https://github.com/PyGithub/PyGithub/blob/master/CONTRIBUTING.md#adding-missing-attributes-for-a-githubobject) section because I wanted to keep a consistent API with the existing one.

Let me know if there is something missing in the PR to accept this one.

This PR supersedes #2449 and solves #2448 and #2486

### CODE REVIEW

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Comment by kang-makes** [comment]
Hi @EnricoMi,

Rebased!

Let me know if you need something more from my side.

**Comment by EnricoMi** [comment]
It still says "This branch is out-of-date with the base branch". Master branch is a moving target.

Can you please "Allow edits and access to secrets by maintainers" in the bottom of the right column on this page, then I can rebase when needed.

**Comment by kang-makes** [comment]
Screenshot 2023-05-09 at 10 11 34

I don't why but I was not able to set it up while creating the PR and I am not able to enable it right now.

I rebased again and I'll be watching notifications in order to rebase as soon as possible.

If I am a blocker, feel free to fork my fork so you own it and you can rebase and merge it. I do not care about attribution/co-authoring/whatever if it means this feature to be merged :)

**Pull request merged**
