### PR TITLE
Update Team.py to get members with role filter

### PR DESCRIPTION
**Pull request by jaypark81**
Hello,

I edited "get_members" function to query with "role" like the following:
 team.get_members(role='maintainer')

### CODE REVIEW

**Comment by jasonwhite** [comment]
Looks good. I know it's a pretty simple change, but would you mind also adding a test for this in `github/tests/Team.py`?

**Comment by jaypark81** [comment]
Yes, sure. here it is:
FYI, gitConnetor function returns github api connector.
Below codes returns every maintainer of every team of every organization of the user in gitConnetor

gconnector = gitConnector()
for org in gconnector.get_user().get_orgs():
    for team in gconnector.get_organization(org.login).get_teams():
      for member in team.get_members(role='maintainer'):
         print member.login

**Comment by calebgroom** [comment]
@jaypark81 Do you mind pulling my commit into this PR? This adds the unit test that @jasonwhite asked for and it also adds the role support to `Team.add_to_members()` so that users who care about roles can set and read it all in one PR.

**Comment by jaypark81** [comment]
No problem. That's better

**Pull request closed without merging**
