### PR TITLE
Make requester a public attribute

### LINKED ISSUE #2071: Provide a way to make a "raw" request
There will always take a while from when new endpoint or parameter is available in the GitHub API until it is supported by a released version of PyGithub.

Something as simple as providing a "public" accessor for __requester that is guaranteed not to change it's name would suffice.
Another possibility would be that the Requester object is, optionally, created by the user and then used to create the GitHub object.

### PR DESCRIPTION
**Pull request by minrk**
There will always be new APIs not yet supported by PyGitHub (e.g. #2718). This adds an escape hatch for users to send requests directly without having to start from scratch or use private APIs while waiting for PyGitHub to add support.

Changes: 

- private `object._requester` `.__requester` is now available via public `.requester` attribute on MainClass, GitHubObject, etc.
- add Requester APIs to docs as public methods, indicating status as stable public APIs

Fixes #2071 which received only positive feedback, but was closed for inactivity.

### CODE REVIEW

**Comment by minrk** [comment]
docformatter hook can't run with pre-commit 4 due to https://github.com/PyCQA/docformatter/pull/287

pre-commit action cannot specify pre-commit version.
pre-commit action is also readily replaced with a single `run`:

```yaml
run: |
  pip install 'pre-commit<4'
  pre-commit run --all-files --show-diff-on-failure --color=always
```

(plus cache, if you want it)

**Review by EnricoMi — COMMENTED** [review]
You could also test the requester property on one GithubObject implementation, e.g. Repository.

**Comment by EnricoMi** [comment]
This looks reasonable to do.

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Comment by EnricoMi** [comment]
Thanks for the contribution!

**Comment by flatherskevin** [comment]
When is this scheduled for release? (Disclaimer I couldn't find release practices elsewhere in the repo, so I figured I would comment directly here)

**Comment by wyardley** [comment]
Seems like this was released in [2.5.0](https://github.com/PyGithub/PyGithub/releases/tag/v2.5.0)

Is this usable on the repo or org objects? I see `repo._requester` but not `repo.requester`?

Seems like a great feature - would be great if there were one or two examples in the docs. Is there a good example of this in use somewhere?

**Pull request merged**
