### PR TITLE
Fix token auth recording so playback can work on Travis

### PR DESCRIPTION
**Pull request by allevin**
For Token authentication when the Authorization header was recorded, it was changed in the recorded file to say "token private_token_removed".

This would work properly for a users playback testing on their own system.

However, when the tests are run on Travis (which apparently uses a basic login method) the tests would fail due to Authorization mis-compares. 

See #516 and #857

Since the user recording data most likely does not care what gets recorded (except to ensure that the authentication data remains private), this simple change will resolve the mis-compare.

### CODE REVIEW

**Comment by sfdye** [comment]
Nice one! This used to be a pain, I have to manually change the "token private_token_removed" to "Basic login_and_password_removed".

**Comment by allevin** [comment]
@sfdye Can you go over this with a fine tooth, and possibly come up with other solutions?

This solution works, however I really didn't like having to change "token private_token_removed" to "Basic login_and_password_removed" in the recorded file.   However to maintain compatibility with all the older existing tests, we have to keep the string "Basic login_and_password_removed" basically everywhere.    I tried other solutions, but this one seemed to cause the least impact.   I just wish we could do something before before the line 180 `self.__testCase.assertEqual(headers, eval(readLine(self.__file)))` that would allow us to keep "token private_token_removed" but just before the check convert it to "Basic login_and_password_removed" without changing a bizillion test results in the repo.

**Comment by allevin** [comment]
ping @sfdye Is there any interest in moving forward with this PR?

**Comment by sfdye** [comment]
Of course @allevin just that I have limited bandwidth now.

**Comment by sfdye** [comment]
un-stale

**Pull request closed without merging**
