### PR TITLE
Add jwt dependency

### LINKED ISSUE #2441: Add cryptography as dependency (for app-based auth)
Using [the new app-based auth ](https://github.com/PyGithub/PyGithub/pull/1986) results to the error below when `cryptography` is not installed. It should be added as a dependency of this.

```
Traceback (most recent call last):
  File "***", line 60, in ***
    github = Github(
  File "/usr/local/lib/python3.9/site-packages/github/MainClass.py", line 122, in __init__
    self.__requester = Requester(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 332, in __init__
    self._refresh_token()
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 396, in _refresh_token
    self.__installation_authorization = self._get_installation_authorization()
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 377, in _get_installation_authorization
    integration = GithubIntegration.GithubIntegration(
  File "/usr/local/lib/python3.9/site-packages/github/GithubIntegration.py", line 52, in __init__
    jwt=self.create_jwt(),
  File "/usr/local/lib/python3.9/site-packages/github/GithubIntegration.py", line 106, in create_jwt
    encrypted = jwt.encode(payload, key=self.private_key, algorithm="RS256")
  File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 67, in encode
    return api_jws.encode(json_payload, key, algorithm, headers, json_encoder)
  File "/usr/local/lib/python3.9/site-packages/jwt/api_jws.py", line 152, in encode
    alg_obj = self.get_algorithm_by_name(algorithm_)
  File "/usr/local/lib/python3.9/site-packages/jwt/api_jws.py", line 91, in get_algorithm_by_name
    raise NotImplementedError(
NotImplementedError: Algorithm 'RS256' could not be found. Do you have cryptography installed?
```

### PR DESCRIPTION
**Pull request by EnricoMi**
Fixes #2441.

### CODE REVIEW

**Comment by s-t-e-v-e-n-k** [comment]
Um, what? There's a pyjwt requirement like two lines above that one -- I was more saying maybe we need pyjwt[something] in the issue.

**Comment by EnricoMi** [comment]
I can't find any use of `PyJWT`, so maybe we can remove that. Or the new code that uses `jwt` has to migrate to `PyJWT`. The latter package has no dependencies.

**Comment by EnricoMi** [comment]
Since our CI uses tox, it does not install more packages then specified, so we are not missing `jwt` from the requirements. I think the user had `jwt` installed, which conflicts with `PyJWT`, which has the same module name `jwt`, so PyGithub called into the wrong module.

**Comment by EnricoMi** [comment]
> Um, what? There's a pyjwt requirement like two lines above that one -- I was more saying maybe we need pyjwt[something] in the issue.

Ah, now I got it. So `PyJWT` has an `crypto` extras, which pulls in `cryptography>=3.4.0`.

**Pull request closed without merging**
