### PR TITLE
Merge `PullRequestMergeStatus` type stub back to source

### PR DESCRIPTION
**Pull request by trim21**

### CODE REVIEW

**Review by Borda — APPROVED** [review]

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Comment by EnricoMi** [comment]
@trim21 updating all these PRs is not helpful in getting the approved ones merged quickly. I'll come back later.

**Comment by trim21** [comment]
> @trim21 updating all these PRs is not helpful in getting the approved ones merged quickly. I'll come back later.

I want to know if ci failed after new prs are merged

**Comment by EnricoMi** [comment]
@trim21 but this blocks me from merging PRs. I have to update each PR individually before merging anyway, I'll let you know if CI fails. Please only update branches if they have conflicts. Otherwise we end up with O(N²) merges, and you have a lot of open PRs.

**Pull request merged**
