### PR TITLE
Add repo.get_stargazers_with_dates()

### LINKED ISSUE #345: Support application/vnd.github.v3.star+json
See https://developer.github.com/v3/activity/starring/#list-stargazers

When requesting a list of stargazers, you can set a custom media type to find out when each user starred your repo. It would be great if pygithub supported this.

### PR DESCRIPTION
**Pull request by danvk**
Fixes #345 

I've included a regression test and ensured that no new PEP8 errors were introduced.

cc @jzelinskie

### CODE REVIEW

**Comment by jzelinskie** [comment]
LGTM

**Comment by danvk** [comment]
Thanks for merging in my PRs! Any chance we could get a v1.25.3 release out with these changes?

**Comment by jzelinskie** [comment]
Look out for one soon. I'd like to get our TravisCI integration working again, so that I can be confident that everything works across the board for different versions of Python.

**Comment by danvk** [comment]
Sounds good, I'll stay tuned.

**Comment by danvk** [comment]
Hey @jzelinskie — it looks like Travis-CI is running your tests successfully on many versions of Python: https://travis-ci.org/PyGithub/PyGithub/builds/85408934

Was there something else you were hoping to have it do?

**Comment by jzelinskie** [comment]
@danvk looks good, I'll try to get a release out when I have the time. I'm a little confused on why Travis isn't building PRs or using the GitHub status API and I don't have permission to play with the configuration because I'm only a maintainer.

**Comment by danvk** [comment]
Yeah, there some settings that only the repo owner can tweak. Good luck with the release. Let me know if there's anything I can do to help.

**Pull request merged**
