### PR TITLE
[WP] Add projects support

### PR DESCRIPTION
**Pull request by isbm**
Hi,
we need projects support. I started adding it. So far you can get them, but do nothing on them. I am continue working on this PR.

Work in progress.

### CODE REVIEW

**Comment by isbm** [comment]
@jacquev6 hey, is this project even alive? Some feedback, please?..

**Comment by isbm** [comment]
@jacquev6 at this very moment of this particular comment, the API completed for listing the following:

- Projects
- Columns in each project
- Cards in each column
- Creator of each card

Example:
```python
from github import Github

TOKEN = '...'
ORG = 'foo'
PRJ = 'bar'

def main():
    conn = Github(TOKEN)
    for project in conn.get_projects(ORG, PRJ):
        print project.number, ":", project.name, project.created_at
        for column in project.get_columns():
            print "\t", column.name
            for card in column.get_cards():
                print "\t\t", card.content_url, "({0})".format(card.creator.login)
        print "-" * 80

if __name__ == '__main__':
    main()
```

I am going to add anytime soon the following:

- Card content by linked issues (e.g. `card.issue.title`)
- edit/delete/create

But if nobody responds half a year to PRs then I don't see any reason to continue on this repo...

**Comment by allevin** [comment]
@isbm Wow, you seem to be wound a little bit tight.  

To answer your question, this project is very active.  If you look at the releases, you can see that new features and bug fixes are being added all the time.  Also an active project does not merge every PR that comes in due to various reasons.  Any PR that is still there after 6 months with no activity means that the developer probably abandoned it.  The people who maintain it are volunteers and do it when they have time available.  They are not paid to maintain this project.  

If you are **PATIENT** and work with the Maintainers, I suspect that your Pull Request will eventually make it into the code base.

By the way, Your pull request failed testing.  I did a quick look over and I don't see any tests for your code.  I know this is important to the project Maintainers, so you should review [CONTRIBUTING](https://github.com/PyGithub/PyGithub/blob/master/CONTRIBUTING.md) and add some tests to your code.

**Comment by isbm** [comment]
@allevin well, the `[WP]` in the title should suggest that it is not yet time to get into testing/merging. But I would expect some feedback on the progress here-there so I don't have to redo everything again.

**Comment by jayfk** [comment]
> But I would expect some feedback on the progress here-there so I don't have to redo everything again.

I would expect a little patience. You are creating a hostile environment and pressure to work on your problem.

That won't work.

**Comment by isbm** [comment]
@jayfk sorry, I was assuming a bit faster tempo, not really to pressure. No problem. At least there are people around, so OK. :wink: Peace.

**Comment by silasary** [comment]
Is this still being worked on?

**Comment by sfdye** [comment]
@silasary I guess if the original author @isbm did not have time to continue, you are free to pick it up.

**Comment by isbm** [comment]
@silasary Well, the original description says:

> But if nobody responds half a year to PRs then I don't see any reason to continue on this repo...

**Comment by sfdye** [comment]
@isbm This project is still actively maintained.

**Comment by isbm** [comment]
Maybe. But in my understanding responding half a year later (or never) equals abandoned. ¯\_(ツ)_/¯

**Comment by jayfk** [comment]
> I am not fan of working on abandoned projects... 😕

Become a maintainer then. It's as simple as that 👯‍♂️

**Pull request closed without merging**
