### PR TITLE
Add support for deleting git refs

### PR DESCRIPTION
**Pull request by rohitpaulk**

### CODE REVIEW

**Comment by jzelinskie** [comment]
Thanks for the PR.
If you add a test, I'll merge this.

**Comment by rohitpaulk** [comment]
Added a test. I tried using the record functionality (replaying github API requests), but kept running into errors. Is there any documentation on how to record a new test? 

One error I ran into was at this point: https://github.com/PyGithub/PyGithub/blob/8a13b274766ccd2bc85df0a0cd5ce3d2932d1aca/github/tests/Framework.py#L199, where `GithubCredentials` wasn't defined. I tried just pasting in my credentials, but that hit another error down the line. Frankly, I wouldn't be surprised if this hasn't been used in a long time...

**Comment by sfdye** [comment]
@rohitpaulk 

> FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/PyGithub/PyGithub/build/lib/github/tests/ReplayData/Repository.testDeleteGitRef.txt'

You need to create a new test data called `Repository.testDeleteGitRef.txt`

**Comment by rohitpaulk** [comment]
@sfdye I understand that :) My question is how to go about adding the file. I wasn't able to get the recording mechanism to work (details in https://github.com/PyGithub/PyGithub/pull/389#issuecomment-368188523).

**Comment by sfdye** [comment]
Sorry to hear. Still, thank you for your contribution. @rohitpaulk

**Pull request closed without merging**
