### PR TITLE
Add team membership add call

### PR DESCRIPTION
**Pull request by xorel**
This should fix https://github.com/jacquev6/PyGithub/issues/280

### CODE REVIEW

**Comment by jacquev6** [comment]
Please see #297.

**Comment by jzelinskie** [comment]
lgtm, but can we get a test for it as well?

**Comment by nhomar** [comment]
I think the test is important also.

**Comment by xorel** [comment]
Sorry, bit busy not to get to this :(

**Comment by jzelinskie** [comment]
Sure, if you ever have time -> #303.

**Pull request merged**
