### PR TITLE
[WIP] Supporting the nested teams preview API (vnd.github.hellcat-preview+json)

### PR DESCRIPTION
**Pull request by jdelic**
This is missing tests, but since it requires an org to be set up with a nested team, I don't think I can add those tests without help.

Anyway, this PR is trying to add support for:
https://developer.github.com/changes/2017-08-30-preview-nested-teams/

Things I am unsure about:
  * `Organization.create_team` in this PR takes a `parent_team_id` parameter, which is what the API expects. Should this be `parent_team` and take a `Team` object? I feel like developers shouldn't have to create a `Team` instance just to set the parent id. However,
  * There are plenty examples for one or the other. On the same method the parameter `repo_names`, which by name kind of implies `Sequence[str]` is then asserted to be of type `Sequence[Repository]`.
  * immediately below it, `delete_hook` takes an `int` id as its parameter and not a `Hook` object.

I could use some opinions or guidance on that.

### CODE REVIEW

**Comment by sfdye** [comment]
See if this helps:
https://github.com/PyGithub/PyGithub/blob/master/CONTRIBUTING.md#automated-tests

**Comment by jdelic** [comment]
When/if #1038 is merged, I will update this PR to add the nested teams API support to the code in it. Otherwise the support for hellcat in this PR is incomplete.

**Comment by jdelic** [comment]
@sfdye as I'm looking to finally adding tests for my PRs and reading `CONTRIBUTING.md`... can you tell me how I can get access to the BeaverSoftware org that is used everywhere so I can use `--record`? 

The alternative would be to 

* set up my own testing org with users, repo and teams and then 
* edit all the tests and then record the results and then 
* edit the results to fir the BeaverSoftware org and then 
* submit the PR

which seems tedious. Can you help?

**Comment by sfdye** [comment]
The current test data is tightly coupled with the `BeaverSoftware` org which does not seem to exist anymore. It can be tricky to replace all the test data with a new org I guess. 

```
{'Authorization': 'Basic login_and_password_removed', 'Accept': 'application/vnd [truncated]...
+ {'Accept': 'application/vnd.github.hellcat-preview+json',
- {'Authorization': 'Basic login_and_password_removed',
? ^
+  'Authorization': 'Basic login_and_password_removed',
? ^
   'User-Agent': 'PyGithub/Python'}
```
Anyway from the Travis log, it seems the error is mainly mismatch between the headers, maybe you can manually add the missing custom `Accept` header and we can see what can be done next?

**Comment by Tioborto** [comment]
Hello, 
We work in Organization and we are very interested by this PR. 
Have you some information about its resolution ?

**Comment by jdelic** [comment]
@Tioborto 
my PRs are really still in progress. I hope that I will soon have time to set up a new testing GitHub org to replace the `BeaverSoftware` org that was used for the tests before. I tried to manually update the tests, but I haven't really gotten it to work.

That said, you can use the PR right now, I've been running a [combined branch of my PRs on PyGithub](https://github.com/optile/PyGithub/tree/optile-head) for [ghconf](https://github.com/optile/ghconf) for a while now.

**Pull request closed without merging**
