### PR TITLE
Add support to vulnerability alert and automated security fixes APIs

### PR DESCRIPTION
**Pull request by cuichenli**
- Add functions to get vulnerability alert information and change the vulnerability alert settings. 
- Add functions to change the automated security fixes settings. 

Note: Those APIs are currently in preview status, feel free to reject it. 

Github API Documents:
- [get vulnerability settings](https://developer.github.com/v3/repos/#check-if-vulnerability-alerts-are-enabled-for-a-repository)
- [enable vulnerability alerts](https://developer.github.com/v3/repos/#enable-vulnerability-alerts)
- [disable vulnerability alerts](https://developer.github.com/v3/repos/#disable-vulnerability-alerts)
- [enable automated security fixes](https://developer.github.com/v3/repos/#enable-automated-security-fixes)
- [disable automated security fixes](https://developer.github.com/v3/repos/#disable-automated-security-fixes)

### CODE REVIEW

**Comment by catmeme** [comment]
Any ETA on this getting merged?

**Comment by cuichenli** [comment]
Hi @s-t-e-v-e-n-k , I have added a few more unit tests. Basically, those checks:
1. when the repository does not exist (error 404)
2. change automated security fix when vulnerability alert is disabled(error 424)
3. get vulnerability when it is turned off(error 404).

**Comment by s-t-e-v-e-n-k** [comment]
How did you rebase this? This is now incredibly difficult to review since it now says 197 files changed.

**Comment by cuichenli** [comment]
😢 I would close this one and raise another PR... Sorry for the inconvenience.

**Comment by s-t-e-v-e-n-k** [comment]
@cuichenli It's no problem! I'm closing this one, and look forward to the fresh PR.

**Pull request closed without merging**
