### PR TITLE
Add allow_redirects option

### LINKED ISSUE #830: Latest release v1.40 has broken get_archive_link
Since the push of v1.40 and change to requests for HTTP instead of httplib, it has broken the get_archive_link method.

Simple Test:
```python
import github
git = github.Github()
repo = git.get_repo('PyGithub/PyGithub')
print(repo.get_archive_link('zipball', 'master'))
``` 

Returns the error:
```
  File "/usr/local/lib/python3.5/site-packages/github/Repository.py", line 1219, in get_archive_link
    return headers["location"]
KeyError: 'location'
```

A quick debug reveals that the requests library is following the request from `GET /repos/:owner/:repo/:archive_format/:ref`, so instead of returning the header info with an expected location, it returns the actual archive zip file:

```json
{'content-disposition': 'attachment; filename=PyGithub-PyGithub-v1.40-0-gd897e86.zip', 'x-content-type-options': 'nosniff', 'access-control-allow-origin': 'https://render.githubusercontent.com', 'x-geo-block-list': '', 'date': 'Thu, 28 Jun 2018 20:49:34 GMT', 'vary': 'Authorization,Accept-Encoding', 'content-length': '3232597', 'strict-transport-security': 'max-age=31536000', 'etag': '"d897e86aa9aa6469971b3e2201ead39cf1aebb62"', 'content-security-policy': "default-src 'none'; style-src 'unsafe-inline'; sandbox", 'content-type': 'application/zip', 'x-github-request-id': 'F53F:2415:309135:4E96ED:5B3549DE', 'x-frame-options': 'deny', 'x-xss-protection': '1; mode=block'}
```

### PR DESCRIPTION
**Pull request by djstein**
Fixes #830

Latest release v1.40 has broken get_archive_link
https://github.com/PyGithub/PyGithub/issues/830

### CODE REVIEW

**Comment by sfdye** [comment]
Would you mind removing the diff introduced by the linter, so we can focus the purpose of this PR?

**Comment by Krafty-Coder** [comment]
This was a long code to review and not sure where you were to work on. The linter made the diff longer which I don't think it was the purpose of the PR.

**Comment by sfdye** [comment]
@djstein I would like to make a new release, if we can get this merged.

**Comment by mfonville** [comment]
Only the changes on line 107 and 133 are relevant; @sfdye I think as maintainer I believe you are able to edit the PR.

**Comment by sfdye** [comment]
@mfonville Yeah technically I can, but I don't want to modify someone else's branch without asking them first. So @djstein do you mind?

**Comment by djstein** [comment]
@sfdye when do we see a build of this going out?

**Comment by sfdye** [comment]
Until #872 progresses, my hands are tied 😞

**Comment by sfdye** [comment]
1.43 is out. `pip install PyGithub --upgrade`

**Pull request merged**
