### PR TITLE
feat: add missing branch protection fields

### LINKED ISSUE #2373: github.BranchProtection.BranchProtection missing 3 attributes
This is duplicate of issue [1716](https://github.com/PyGithub/PyGithub/issues/1716) (closed by StaleBot).

GitHub api provides to do the following:

    required_linear_history: true,
    allow_force_pushes: true,
    allow_deletions: true

https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-branch-protection

The functions related to this 3 branch protection rules are not added in the class mentioned in the title.

PR #1723 was closed by the author, but this feature is still missing.

### PR DESCRIPTION
**Pull request by ruben-chainalysis**
Fixes #2373 

Add new BranchProtection options listed here: https://developer.github.com/v3/repos/branches/

    `required_linear_history`
    `allow_force_pushes`
    `allow_deletions`

Replica of #1723 (and like the original contributor, running the tests locally is giving me pain).

### CODE REVIEW

**Comment by harry-unlikelyai** [comment]
Can you add `lock_branch` to this?

**Comment by ruben-chainalysis** [comment]
> Can you add `lock_branch` to this?
Sure, I only needed 2 of the missing ones and didn't notice there are more protections not mentioned in the original, I'll take a look, seems in scope for this (mentioning #2299 because we might fix that one too).

> Edit: Also from what I can gather, you may need to edit the `tests/ReplayData` to get the CI passing

I'll give it a go, thanks for the suggestion! Any help with this would be appreciated, as this PR might take some time to get merged, I'm working on using requests directly as a workaround and that takes precedence.

**Comment by harry-unlikelyai** [comment]
I have done this now upstream from here in [this PR](https://github.com/PyGithub/PyGithub/pull/2378) which looks like it is passing!

**Comment by ruben-chainalysis** [comment]
Closing in favour of #2378

**Pull request closed without merging**
