### PR TITLE
Add support for the preview of the Vulnerability Alert APIs

### PR DESCRIPTION
**Pull request by chrihala**
* Add support for the preview APIs related to Vulnerability Alerts on repositories (https://developer.github.com/changes/2019-04-24-vulnerability-alerts/) 
* Added support for three API endpoints:
    * `GET /repos/:owner/:repo/vulnerability-alerts`- Returns the status of Security Alerts for the repo
    * `PUT /repos/:owner/:repo/vulnerability-alerts` - Enable Security Alerts for the repo
    * `DELETE` /repos/:owner/:repo/vulnerability-alerts` - Disable Security Alerts for the repo

I had a need for this so I added it. Feel free to reject this if you want to wait for full official support for the APIs. 

The APIs require owner permissions for the repository in question. I haven't written any checks to see if permissions are correct or not.

### CODE REVIEW

**Comment by sfdye** [comment]
Hi @chrihala Thank you very much for your PR. It would be helpful if you can add a unit test. You can refer to the contribution [docs](https://github.com/PyGithub/PyGithub/blob/master/CONTRIBUTING.md#automated-tests) for instructions.

**Comment by fatbasstard** [comment]
Can't find API documentation at the moment, but for the Security Alerts you can specify which teams (with `write` access) have access to the alerts:

image

Would be nice to have this in as well

**Comment by ashemedai** [comment]
> Would be nice to have this in as well

Did some quick digging, doesn't look like they expose this functionality in any way at the moment via an API endpoint. :(

**Comment by chrihala** [comment]
I'm making an attempt at writing unit tests for this, but I'm not sure how to run these individual tests. 
E.g. `python -m tests Repository.testGetStatusOfVulnerabilityAlerts` doesn't work for me. 

Also, the tests need admin-level access to a repository to work. Any suggestions on how I should do this?

**Comment by s-t-e-v-e-n-k** [comment]
Admin access to a repository is fine -- the tests only really care about the JSON reponses from the GitHub API that the replay data returns, so as long as that data is populated, your tests will be fine.

And indeed, looking at your test failures, you don't have any replay data, hence the failures.

**Comment by chrihala** [comment]
I've added the unit tests and recorded a run of the tests. Does this look alright?

**Comment by testworksau** [comment]
It looks like there's a superset of this change in https://github.com/PyGithub/PyGithub/pull/1173

**Comment by chrihala** [comment]
Yeah, #1173 is superior to this one. I've tested it and it does what this one does and more, so I'll go ahead and close this one. Hopefully #1173 will be merged soon :)

**Pull request closed without merging**
