### PR TITLE
Add verify option for to requests wrapper

### LINKED ISSUE #746: add ignore SSL option for github enterprise accessibility
Please provide a 'verify=False' kinda flag for accessing enterprise servers with self signed certificates.

### PR DESCRIPTION
**Pull request by mikeage**
Closes #746

### CODE REVIEW

**Comment by sfdye** [comment]
Looks good. Were you able to test this?

**Comment by mikeage** [comment]
Yes, but only with giving a `base_url` to a non-Github site. Our GHE server has a proper certificate, so instead, I tried connecting to https://self-signed.badssl.com and confirmed that it gave an SSL error by default, but a 404 when I passed `verify=False`.

**Comment by mikeage** [comment]
@pinakc, can you test this on your environment?

**Comment by sfdye** [comment]
I've tested this in my GHE instance, works well. Also playing nice with `github.com`.

**Pull request merged**
