### PR TITLE
Add parameters to Repository.get_workflow_runs

### PR DESCRIPTION
**Pull request by Felixoid**
`exclude_pull_requests` and `head_sha` are valid parameters, see  
https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-repository

### CODE REVIEW

**Review by EnricoMi — APPROVED** [review]
@sfdye @s-t-e-v-e-n-k this looks pretty straight forward and non-controversal

**Comment by ankitvgupta** [comment]
I was looking for this as well - is there anything I could do to help get this across the finish line?

**Comment by Felixoid** [comment]
Dear @sfdye and @s-t-e-v-e-n-k, I've updated the upstream, and it looks pretty well. Can you consider merging it?

**Comment by Felixoid** [comment]
Thanks a lot!

**Pull request merged**
