### PR TITLE
Add app_push_restrictions support for branch-protections

### PR DESCRIPTION
**Pull request by pabelanger**
It is also possible to add app_push_restrictions for branch protections,
this adds support for it.

Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by s-t-e-v-e-n-k** [comment]
This is missing replay data for the added test methods, look at the --record option for pytest. However, the code changes look fine to me.

**Comment by pabelanger** [comment]
@s-t-e-v-e-n-k any pointers on how replay data works? I guess I would run some sort of API commands manually, and save the http output?

**Comment by s-t-e-v-e-n-k** [comment]
https://github.com/PyGithub/PyGithub/blob/master/CONTRIBUTING.md#automated-tests

**Comment by pabelanger** [comment]
Thanks, I think we can close this in favor of https://github.com/PyGithub/PyGithub/pull/1771 I left some comments there too

**Pull request closed without merging**
