### PR TITLE
Continue the PR #1899

### PR DESCRIPTION
**Pull request by Felixoid**
Hello. I'd like to have the #1899 finished and #1898 fixed.

The `release` payload has assets and it's a bit painful to have other unnecessary requests spent on getting the assets

### CODE REVIEW

**Comment by Felixoid** [comment]
Codecov hasn't updated the comment, the coverage is not changed actually, see the [View full report at Codecov](https://codecov.io/gh/PyGithub/PyGithub/pull/2386?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PyGithub).

**Comment by Felixoid** [comment]
Dear @sfdye and @s-t-e-v-e-n-k, is the project active? Can you be so nice and review the PR, please?

**Comment by Felixoid** [comment]
I think I've mentioned Steve accidentally. But maybe @jacquev6, @JPWKU or @adamtheturtle could help?

**Review by sfdye — APPROVED** [review]

**Comment by Felixoid** [comment]
Thanks a lot!

Do you need some help in voluntarily reviewing PRs maybe? I am a little bit into the code right now, since starting using it intensively in our CI/CD system. I can provide some time into the code base.

**Comment by sfdye** [comment]
@Felixoid Help is always welcome. Feel free to move the project forward in any way.

**Comment by Felixoid** [comment]
Thanks, I didn't know one can approve PR w/ just default permissions!

**Pull request merged**
