### PR TITLE
Add `reset` to `__repr__` for `Rate` type

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Attempt number two, this one should be correct.

### CODE REVIEW

**Comment by s-t-e-v-e-n-k** [comment]
I like it! I think we need a repr test, I can provide pointers, or merge this and add one myself.

**Comment by JLLeitschuh** [comment]
If you could merge this and add the test, that would be appreciated. I'm barely a python user so you'd probably do a far better job creating this test than I would.

**Comment by s-t-e-v-e-n-k** [comment]
I'm going to close this PR, and propose a new one including a test. I'll be sure to credit you, and many thanks @JLLeitschuh!

**Comment by JLLeitschuh** [comment]
Glad to help! Cheers!

**Pull request closed without merging**
