### PR TITLE
Implement __len__ on the PaginatedList

### PR DESCRIPTION
**Pull request by pgmillon**
See #415

### CODE REVIEW

**Comment by RSully** [comment]
I feel like this is misleading, as if you iterate over a PaginatedList you're going to get more entries than the length of elements, since it will automatically fetch more pages.

**Comment by jzelinskie** [comment]
@RSully `page_length`?

**Comment by RSully** [comment]
Eh that sounds like the length of the page itself. I might propose cached_length or element_count?

**Comment by pgmillon** [comment]
If I get this right, the issue is that:
> if you iterate over a PaginatedList you're going to get more entries than the length of elements
Let me make you another proposal with the next commit.

**Pull request closed without merging**
