### PR TITLE
Add support for missing branch protections

### PR DESCRIPTION
**Pull request by rkleinman-hpe**
Add linear history, allow force pushes, allow deletions, and required_conversation_resolution to the existing branch protections. See issue PyGithub#1716.

### CODE REVIEW

**Comment by rkleinman-hpe** [comment]
I am not sure if I need to add new tests in a separate file, or include new tests in tests/Branch.py. Any pointers are greatly appreciated.

**Comment by s-t-e-v-e-n-k** [comment]
Either is fine, whatever is easier.

**Comment by treee111** [comment]
Hi @rkleinman-hpe I also would be happy to have those fields available.
Can I assist you with this PR?

**Comment by jekwesco** [comment]
> Hi @rkleinman-hpe I also would be happy to have those fields available. Can I assist you with this PR?

I'd suggest doing a PR yourself since this one seems dead in the water. I'm tempted to do so because I also need these fields ;)

**Pull request closed without merging**
