### PR TITLE
Fix hashing in python3

### PR DESCRIPTION
**Pull request by python273**
```python
from github import Github

me = Github(' token ').get_user()

repo = list(me.get_repos())[-1]

print({repo: 'test'})
"""
Traceback (most recent call last):
  File ".../PyGithub/test_hashable.py", line 9, in <module>
    print({repo: 'test'})
TypeError: unhashable type: 'Repository'
"""

user_repos = {}

for user in repo.get_stargazers():
    user_repos[user] = 'test'
    """
    Traceback (most recent call last):
      File ".../PyGithub/test_hashable.py", line 20, in <module>
        user_repos[user] = 'test'
    TypeError: unhashable type: 'NamedUser'
    """
    break

print(user_repos)
```

### CODE REVIEW

**Comment by Croydon** [comment]
This should be merged instead of getting closed.

**Comment by sfdye** [comment]
Sure. Will revisit.

**Comment by Croydon** [comment]
Ping.

**Comment by Croydon** [comment]
..... 🙄

**Comment by Croydon** [comment]
@sfdye

**Comment by Croydon** [comment]
Hi! This is my generic reply for every issue which is still relevant and is on the edge of getting closed by a stale bot.

**Comment by garfieldG** [comment]
Hi, 
@Croydon anything new regarding this issue?
I encountered the same problem with Issue being an unhashable type.
There's a commit fixing it just for NamedUser, but not other types.
the fix in this commit helped me.

**Pull request closed without merging**
