### PR TITLE
Adopt black as code formatter

### PR DESCRIPTION
**Pull request by sfdye**
This PR proposes to use [black](https://github.com/psf/black) as the code formatter. 

- [x] Apply `black` to whole code base
- [x] Apply `isort` to whole code base
- [x] Make flake8 compatible with black
- [ ] Update docs
- [ ] Update PR template
- [ ] Enforce black on CI
- [ ] Enforce isort on CI
- [ ] Add pre-commit 
- [ ] Add .ignore-rev-files

### CODE REVIEW

**Comment by sfdye** [comment]
@s-t-e-v-e-n-k Let me know if you have any strong opinion on this PR

**Comment by s-t-e-v-e-n-k** [comment]
@sfdye My strong opinion is this all looks amazing! If you're happy with it, I say let's land it and cut a release.

**Comment by sfdye** [comment]
@s-t-e-v-e-n-k Thanks, merged into master. In the meantime, please hold off merging any open PR into master until I enforce black and isort on CI.

**Comment by s-t-e-v-e-n-k** [comment]
@sfdye Noted. I have a large branch to drop 2.7 support locally, but we need a release first ,so drop me a line when you're ready for me to pull the trigger for that (there's a breaking change we need to document carefully as well as stating this will be the last release to support 2.7)

**Pull request merged**
