### PR TITLE
Add missing attributes to `BranchProtection` Jan 2024

### PR DESCRIPTION
**Pull request by jodelasur**
Fixes https://github.com/PyGithub/PyGithub/issues/2862. Also added other missing attributes. 

All attributes added:
- `allow_force_pushes`
- `allow_deletions`
- `required_conversation_resolution`
- `lock_branch`
- `allow_fork_syncing`

Used `scripts/add_attribute` and added attribute tests accordingly using existing replay data.

### CODE REVIEW

**Review by EnricoMi — CHANGES_REQUESTED** [review]
While you are there, can you add all other missing attributes as well, please?

https://docs.github.com/en/rest/branches/branch-protection#get-branch-protection

**Comment by JayChanggithub** [comment]
"Hi @jodelasur, we're interested in adopting these functionalities. Could you expedite the merging of the pull requests, or do you have any suggestions for directly incorporating these modules? Thanks!"

**Comment by jodelasur** [comment]
@JayChanggithub , waiting for further review from @EnricoMi to have this merged.

**Comment by treee111** [comment]
also fixes https://github.com/PyGithub/PyGithub/issues/2373 in my opinion.
thanks for your work @jodelasur 👍

**Comment by EnricoMi** [comment]
Superseded by #2873, added you as co-author to appreciate your contribution.

**Pull request closed without merging**
