### PR TITLE
Add support for environments

### PR DESCRIPTION
**Pull request by alson**
[Environments](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) are a feature in Github that allows setting up deployment rules, like manual approval, per repository. Because they can only be configured per repository, this makes automating their management particularly important for many-repository micro-service application. This PR adds support for getting, creating, updating and deleting environments as documented [here](https://docs.github.com/en/rest/deployments/environments).

This partially implements the features requested by [issue 2067](https://github.com/PyGithub/PyGithub/issues/2067) (environments, but not environment secrets).

### CODE REVIEW

**Comment by alson** [comment]
The linter CI run failed, but the failure is that git is prompting for credentials to clone some packages from Gitlab. So that does not look related to my changes in any way, since I didn't touch the build or requirements files. Locally I get the same error with PyGithub:master.

**Comment by willejs** [comment]
I would love to see this merged somehow!

**Comment by Paul-AUB** [comment]
Same, I'm very interested in this feature !

**Review by EnricoMi — CHANGES_REQUESTED** [review]
Looks good.

We are migrating away from `.pyi` files. Can you please merge all typing information from **new** `.pyi` files (so not `Repository.pyi`) into the corresponding `.py` files? This will help not building up tech debt.

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Pull request merged**
