### PR TITLE
Added option to create review for Pull request

### PR DESCRIPTION
**Pull request by gshefer**
Added option to create review for Pull request.
With this code you have the ability to create a review object and also specify the event (APPROVE, REQUIRE_CHANGES, ...) which you don't have in reviewer request.

### CODE REVIEW

**Comment by dkalowsk** [comment]
Have you looked at: https://github.com/PyGithub/PyGithub/pull/598 ?

**Comment by gshefer** [comment]
@dkalowsk yes, I also approved the PR, but this PR is different, it implements different things. in #598 you have the ability to create reviewer requests, in this one you have the ability to create a review object and also specify the event (APPROVE, REQUIRE_CHANGES, ...) which you don't have in reviewer request.

**Comment by gshefer** [comment]
@dkalowsk @sfdye I created unit tests but it seems like I have some issues with permissions or something, could you please take a look? thanks!

**Comment by sfdye** [comment]
@gshefer What do you mean by permission issue? 

All I can see is that the test is failing on travis:
> ERROR: testAttributes (github.tests.PullRequestReview.PullRequestReview)

**Comment by gshefer** [comment]
@sfdye I'm not sure, I don't understand why it fails there... I'm trying to get the commit and create a review.

**Comment by sfdye** [comment]
@gshefer Did it work for you locally?

**Comment by gshefer** [comment]
@sfdye yes

**Comment by electrofelix** [comment]
@gshefer did you forget to include the ReplayData for github/tests/ReplayData/PullRequestReview.setUp.txt?

Looks like you need to run:
```
python -m github.tests PullRequestReview.testAttributes --record
```

I'd love to be able to use this library for some integration/workflow testing and this method would be immensely useful for test case building.

**Comment by allevin** [comment]
@gshefer Thanks for working on this.  I wrote the original PR #538 for reading reviews, but didn't need to create them.  However the needs on my project has changed, and I was just about to start work on this exact same task.  You beat me to the punch.

The problem I ran into during testing of of #538 was that I needed a PR to have reviews assigned to them.  I did not have repo permissions to make that happen, but @jzelinskie was able to resolve it for me.

On this PR, I beleive you will need to be able to add a review to a PR (required for the record process mentioned by @electrofelix).  However, unless you have write permissions to the repo I don't think this will work.  Perhaps @sfdye can help out here?

**Comment by gshefer** [comment]
@allevin I added the relevant content to github/tests/ReplayData/PullRequestReview.setUp.txt as @electrofelix said. @sfdye @dkalowsk any idea why it fails? I tested this locally and everything is working well. if it's indeed permissions issue, what should I do?
Note that I tested this locally in another repo and it seems to be working fine.

**Comment by sfdye** [comment]
@gshefer I've cloned your fork on my machine but unfortunately the tests are failing for the same reasons as they were on travis. I think there might be some issues with your unit tests or implementation. You wanna check again?

**Comment by electrofelix** [comment]
@gshefer I believe that this needs a combination of #731 to include some missing attributes required to compare PullRequestReview type objects, and an additional test attributes file github/tests/ReplayData/PullRequestReview.testAttributes.txt.

If you take a look at https://github.com/electrofelix/PyGithub/commit/739a7887c0007a37c8b5410eb6a6f14988245d8b it's now working for me when run against this repo, but I didn't want to replace this PR with another duplicate.

**Comment by sfdye** [comment]
I just merged #731, @gshefer you can pull the change from master now 🎉 Thanks @electrofelix for the quick help.

**Comment by sfdye** [comment]
Tests still failing :(  BTW we need a PR to remove the custom headers as PR review API is out of beta now. Any volunteers?

________________________________

**Comment by gshefer** [comment]
@sfdye Yep, unfortunately, I'm not sure what is the reason for this failure. The post request I added for the review creation is some post I added in some repository that I have permission and just changed few attributes. but now I'm not sure what is the issue. I think it's something that caused by https://github.com/PyGithub/PyGithub/blob/master/github/tests/Framework.py#L147, any idea? probably we have to __really__ create a review object and copy the rest data to ReplyData?
Thanks

**Comment by gshefer** [comment]
@sfdye Thanks a lot :-)

**Comment by sfdye** [comment]
@gshefer No worries, thank you for your contribution 😄

**Pull request merged**
