### PR TITLE
Support custom base_url for get_installation

### PR DESCRIPTION
**Pull request by nydr**

### CODE REVIEW

**Comment by nydr** [comment]
Bugfix of `get_installation` which is hardcoded to use `DEFAULT_BASE_URL` which means it doesn't work with Github enterprise app installations

**Comment by s-t-e-v-e-n-k** [comment]
Looks great, could you add a test or two covering the default case as well as one covering the overridden base_url case?

**Comment by nydr** [comment]
If anyone is able to add test feel free to take over this PR. Unfortunately I don't have a lot of time to spare and I don't have a dev environment setup for this project so I'm unable to do so.

**Comment by s-t-e-v-e-n-k** [comment]
I've finally had time to look at this. Closing this PR and replacing it with my own. Thanks for your contribution!

**Pull request closed without merging**
