### PR TITLE
Add get_review_comments to PullRequestReview

### PR DESCRIPTION
**Pull request by urishalit**
I tried adding a test for this, and frankly understood you guys will do it much faster than me... It seems quite simple if you know exactly what to put in the txt file.

Would appreciate if you can merge this and publish a new version, thanks.

### CODE REVIEW

**Comment by urishalit** [comment]
@TravisBuddy Can someone help me with the test?

**Comment by s-t-e-v-e-n-k** [comment]
This API endpoint is already exported as ``PullRequest.get_single_review_comments(id)``. Which also isn't tested (sigh!)

**Comment by urishalit** [comment]
> This API endpoint is already exported as `PullRequest.get_single_review_comments(id)`. Which also isn't tested (sigh!)

Could be, but that isn't the straightforward way to do it. You have a review, you want to get the comments for it. Why not add this as well?

**Comment by s-t-e-v-e-n-k** [comment]
It calls exactly the same API endpoint as your PR, and is already landed. To replicate your functionality just call ''pr.get_single_review_comments(pr.id)`` ?

**Comment by s-t-e-v-e-n-k** [comment]
To put it another way, why would I merge code that looks 99% identical to mean you don't have to pass one argument?

**Comment by urishalit** [comment]
What you are saying is this:

```
pull = repo.get_pull(123)
for review in pull.get_reviews():
     pull. get_single_review_comments(review.id)
```

While what I am suggesting is this:

```
pull = repo.get_pull(123)
for review in pull.get_reviews():
     review.get_review_comments()
```

I think my solution is more correct for a few reasons:

1. The comments are properties of the review not the pull, so it should be reflected as such.
2. If for instance I want to call function/store reviews in state - in your way I need to also store the pull with it (as from a review you can't know for which pull it is) - this is quite cumbersome.

But in the end, 1 is the reason - the objects should reflect the data model, the api is to get comments of a review not a pull thus the function should be on the review and not the pull

**Pull request closed without merging**
