### PR TITLE
Code review bodies are optional in some cases.

### PR DESCRIPTION
**Pull request by Ferada**
The body of a pull request review is optional for the `APPROVE` and `PENDING` events.

### CODE REVIEW

**Comment by s-t-e-v-e-n-k** [comment]
Looks okay to me, requires a unit test.

**Comment by Ferada** [comment]
> Looks okay to me, requires a unit test.

Working on it, don't have a Python 2 available at the moment.

**Comment by Ferada** [comment]
@s-t-e-v-e-n-k so, I had to find a pull request that I could approve (can't approve your own). Looks okay like this? The test case _does_ fail if the changed code isn't present, otherwise I'll simply return 200, nothing much more to check there I think.

**Comment by Ferada** [comment]
Not stale at all, a bit dry perhaps. Will fix that conflict in a bit.

**Comment by Ferada** [comment]
Cheers!

**Pull request merged**
